def buzz_monograms():
     return [
'driv',
'team',
'självständ',
'fokus',
'väx',
'engager',
'positiv',
'flexibel',
'engagemang',
'utmaning',
'noggran',
'brinn',

'teamet',
'ansvarstag',
'motiver',
'utman',
'samarbetsförmåg',
'delakt',
'lyhörd',
'kommunikativ',
'ambition',
'nyfik',

'initiativ',
'utvecklingsmöj',
'självgåend',
'fantastisk',
'ansvarsfull',
'prestigelös',
'unik',
'nätverk',
'kreativ',

'fokuser',
'effektiv',
'bred',
'glad',
'dukt',
'inspirer',
'flexibilitet',
'stimuler',
'energi',
'frihet',
'älsk',
'effektivt',
'lagspel',

'lösningsorienter',
'värdering',
'meningsfull',
'genuint',
'brett',
'utåtrik',
'värdegrund',
'professionellt',
'professionell',
'match',
'kul',

'gemenskap',
'bravur',
'stabil',

'innovativ',
'stresstå',
'drivkraft',
'utåt',
'initiativtag',
'integritet',


'dynamisk',
'målsättning',
'eftersträv',
'värder',
'innovation',
'plattform',
'nytänk',
'ödmjuk',
'företagskultur',
'arbetsklim',
'könsfördelning',
'flexibl',
'arbetsglädj',
'målinrik',
'tävlingsinrik',
'problemlös',
'problemlösning',
'ledord',
'karriärmöj',


'kontaktyt',
'spel',
'kundbemöt',
'effektivitet',
'smid',
'framkant',
'analy',
'systematisk',
'potential',
'jämställd',
'målgrupp',
'lösningsfokuser',
'öppen',
'attityd',
'talang',

'ambitiös',
'drömjobb',
'drivn',
'nyfiken',
'management',
'digitalisering',
'individuellt',
'förutsät',
'covid',
'agil',
'expander',
'vidareutveckl',
'stress',
'familjär',
'skratt',


'kundnöjd',
'förbättringsarbet',
'balan',
'ordningsam',
'fräsch',
'kommunikationsförmåg',
'hemifrån',
'sammansvets',
'trivsel',
'kreativitet',

'generös',
'kliv',
'inklusiv',
'resultatinrik',
'stjärn',

'initiativrik',
'arbetsmoral',
'värdeord',
'kontaktnät',
'karriärsteg',
'prisbelönt',
'account',
'säkerhetsmedvet',
'expansion',

'samarbetsvil',
'trivsam',
'sammanhållning',
'glimt',

'bankid',

'servicekänsl',
'innovativt',
'lojal',
'anpassningsbar',
'familjärt',

'relationsskap',
'motivation',
'omställning',
'tålamod',
'rättvis',
'tålmod',
'drömjobbet',
'dediker',
'stjärnsälj',
'kundfokus',
'teamkänsl',
'fartfyllt',
'empatisk',
'uppstart',
'nyckelroll',
'fartfylld',
'glädjesprid',
'passioner',


'bollplank',
'kundfokuser',
'lösningsinrik',
'kärnvärd',
'tävnlingsinrik',

     ]

def buzz_bigrams():
     return [
('person', 'egenskap'),
('gör', 'skilln'),
('arbet', 'självständ'),
('god', 'samarbetsförmåg'),
('högt', 'tempo'),
('rätt', 'person'),
('vill', 'utveckl'),
('möj', 'utveckl'),
('eget', 'ansv'),
('nya', 'utmaning'),
('egn', 'initiativ'),
('stort', 'intress'),
('person', 'utveckling'),
('person', 'utveckl'),
('lätt', 'samarbet'),
('genuint', 'intress'),
('möj', 'påverk'),

('tar', 'ansv'),
('vill', 'bidr'),
('kund', 'behov'),
('positiv', 'inställning'),
('stort', 'engagemang'),
('kommunikativ', 'förmåg'),
('varier', 'arbetsuppgift'),
('tillsamman', 'skap'),
('god', 'servic'),
('engager', 'medarbet'),

('stort', 'ansv'),
('social', 'kompet'),
('god', 'kommunikativ'),
('möj', 'väx'),
('lill', 'extr'),
('erbjud', 'spänn'),
('högt', 'tak'),
('samarbet', 'kolleg'),
('jämn', 'könsfördelning'),
('erbjud', 'möj'),
('ser', 'möj'),

('frihet', 'ansv'),
('lös', 'problem'),
('god', 'arbetsmiljö'),
('utveckl', 'roll'),
('ta', 'chans'),
('erfaren', 'led'),
('skap', 'förutsättning'),
('utveckl', 'tillsamman'),
('engager', 'kolleg'),
('ger', 'möj'),
('omväxl', 'arbet'),
('stor', 'frihet'),
('social', 'förmåg'),

('ständ', 'förbättring'),
('brinn', 'intress'),
('god', 'stämning'),
('gemensamm', 'mål'),
('mång', 'kontaktyt'),
('erbjud', 'trygg'),
('skap', 'värd'),
('utveckl', 'yrkesroll'),
('gott', 'samarbet'),
('ständ', 'utveckl'),
('högt', 'arbetstempo'),
('boll', 'luft'),
('gör', 'karriär'),
('verksam', 'tillsamman'),
('hitt', 'perfek'),
('steg', 'karriär'),

('tänk', 'nytt'),
('hög', 'integritet'),
('medarbet', 'triv'),
('kul', 'jobbet'),
('form', 'framtid'),
('vikt', 'egenskap'),
('strukturer', 'arbetssät'),
('bra', 'samarbet'),
('arbet', 'effektivt'),
('triv', 'jobb'),
('ständ', 'utveckling'),
('arbet', 'varier'),
('hög', 'arbetsmoral'),
('stark', 'vilj'),
('ta', 'initiativ'),
('god', 'kommunikationsförmåg'),
('känn', 'bekväm'),
('person', 'engagemang'),
('bäst', 'servic'),

('stort', 'nätverk'),
('förmåg', 'samarbet'),
('spänn', 'arbet'),
('intress', 'människ'),
('sammansvets', 'team'),
('positiv', 'attityd'),
('spänn', 'utmaning'),
('rätt', 'inställning'),
('snabbt', 'väx'),
('mång', 'boll'),
('spänn', 'uppdrag'),
('hitt', 'drömjobb'),
('jobb', 'självständ'),
('social', 'person'),
('gill', 'utmaning'),

('känsl', 'servic'),
('rätt', 'förutsättning'),
('självständ', 'team'),
('erbjud', 'stimuler'),
('triv', 'bra'),
('balan', 'arbet'),

('hög', 'ambition'),
('glad', 'positiv'),
('vilj', 'utveckl'),
('skap', 'relation'),
('gott', 'arbetsklim'),
('egn', 'beslut'),
('trygg', 'person'),
('lil', 'extr'),
('bra', 'tempo'),

('social', 'utåtrik'),
('stimuler', 'arbet'),
('glimt', 'ögat'),
('klättr', 'karriärsteg'),

('socialt', 'begåv'),
('strukturer', 'noggran'),
('stort', 'driv'),

('värld', 'bäst'),
('hög', 'servicenivå'),

('kul', 'tillsamman'),
('noggran', 'positiv'),
('utåtrik', 'person'),
('gill', 'högt'),
('väx', 'knak'),
('utveckl', 'person'),

('drivn', 'medarbet'),
('stark', 'engagemang'),

('spänn', 'projek'),
('jobb', 'problemlösning'),
('bra', 'sammanhållning')

     ]