def buzz_monograms():
     return [
'driv',
'team',
'självständ',
'fokus',
'väx',
'engager',
'positiv',
'social',
'flexibel',
'engagemang',
'utmaning',
'noggran',
'brinn',
'anpass',
'mångfald',
'arbetsmiljö',

'teamet',
'ansvarstag',
'motiver',
'kommunicer',
'utman',
'samarbetsförmåg',
'delakt',
'lyhörd',
'tempo',
'kommunikativ',
'ambition',
'nyfik',

'initiativ',
'utvecklingsmöj',
'självgåend',
'fantastisk',
'ansvarsfull',
'ledarskap',
'prestigelös',
'praktisk',
'unik',
'stolt',
'nätverk',
'aktuell',
'kreativ',

'fokuser',
'effektiv',
'bred',
'glad',
'dukt',
'inspirer',
'flexibilitet',
'stimuler',
'energi',
'inställning',
'frihet',
'strategisk',
'älsk',
'coach',
'glädj',
'effektivt',
'forskning',
'hållbar',
'tillväxt',
'hållb',
'lagspel',

'lösningsorienter',
'framgångsrik',
'positivt',
'värdering',
'organiser',
'samverkan',
'tvek',
'meningsfull',
'genuint',
'kompetensutveckling',
'kompetens',
'obehindr',
'brett',
'utåtrik',
'värdegrund',
'professionellt',
'human',
'match',
'kul',
'kvalité',

     ]

def buzz_bigrams():
     return [
('person', 'egenskap'),
('gör', 'skilln'),
('arbet', 'självständ'),
('god', 'samarbetsförmåg'),
('högt', 'tempo'),
('rätt', 'person'),
('vill', 'utveckl'),
('möj', 'utveckl'),
('stor', 'möj'),
('uppsat', 'mål'),
('eget', 'ansv'),
('nya', 'utmaning'),
('egn', 'initiativ'),
('stort', 'intress'),
('arbet', 'team'),
('person', 'utveckling'),
('lätt', 'samarbet'),
('genuint', 'intress'),
('möj', 'påverk'),

('tar', 'ansv'),
('vill', 'bidr'),
('samarbet', 'andr'),
('utveckl', 'arbet'),
('kund', 'behov'),
('positiv', 'inställning'),
('stort', 'engagemang'),
('kommunikativ', 'förmåg'),
('väx', 'företag'),
('varier', 'arbetsuppgift'),
('tillsamman', 'skap'),
('god', 'servic'),
('engager', 'medarbet'),
('god', 'datorvan'),

('arbet', 'högt'),
('stort', 'ansv'),
('social', 'kompet'),
('god', 'kommunikativ'),
('möj', 'väx'),
('lill', 'extr'),
('lär', 'nya'),
('nå', 'mål'),
('erbjud', 'spänn'),
('del', 'team'),
('högt', 'tak'),
('hel', 'värld'),
('samarbet', 'kolleg'),
('driv', 'arbet'),
('jämn', 'könsfördelning'),
('hos', 'familj'),
('hållb', 'utveckling'),
('teknisk', 'intress'),
('erbjud', 'möj'),
('ser', 'möj'),
('långsikt', 'relation'),

('social', 'medi'),
('snabb', 'väx'),
('ansik', 'utåt'),
('driv', 'utveckling'),
('självständ', 'arbet'),
('fokuser', 'kompet'),
('frihet', 'ansv'),
('lag', 'logistik'),
('öpp', 'fokuser'),
('lös', 'problem'),
('ordning', 'red'),
('god', 'arbetsmiljö'),
('utveckl', 'roll'),
('ta', 'chans'),
('väx', 'utveckl'),
('stort', 'fokus'),
('sök', 'driv'),
('erfaren', 'led'),
('skap', 'förutsättning'),
('håll', 'hög'),

('båd', 'självständ'),
('varier', 'arbet'),
('bygg', 'relation'),
('effektivt', 'sätt'),
('god', 'social'),
('utveckl', 'tillsamman'),
('analytisk', 'förmåg'),
('jobb', 'team'),
('engager', 'kolleg'),
('noggran', 'strukturer'),

('person', 'driv'),
('driv', 'utveckl'),
('ger', 'möj'),
('omväxl', 'arbet'),
('stor', 'frihet'),
('social', 'förmåg'),
('driv', 'person'),


     ]