def buzz_monograms():
     return [
'driv',
'team',
'självständ',
'fokus',
'väx',
'engager',
'positiv',
'social',
'flexibel',
'engagemang',
'utmaning',
'noggran',
'brinn',
'anpass',
'mångfald',
'arbetsmiljö',

'teamet',
'ansvarstag',
'motiver',
'kommunicer',
'utman',
'samarbetsförmåg',
'delakt',
'lyhörd',
'tempo',
'kommunikativ',
'ambition',
'nyfik',

'initiativ',
'utvecklingsmöj',
'självgåend',
'fantastisk',
'ansvarsfull',
'ledarskap',
'prestigelös',
'praktisk',
'unik',
'stolt',
'nätverk',
'aktuell',
'kreativ',

'fokuser',
'effektiv',
'bred',
'glad',
'dukt',
'inspirer',
'flexibilitet',
'stimuler',
'energi',
'inställning',
'frihet',
'strategisk',
'älsk',
'coach',
'glädj',
'effektivt',
'forskning',
'hållbar',
'tillväxt',
'hållb',
'lagspel',

'lösningsorienter',
'framgångsrik',
'positivt',
'värdering',
'organiser',
'samverkan',
'tvek',
'meningsfull',
'genuint',
'kompetensutveckling',
'kompetens',
'obehindr',
'brett',
'utåtrik',
'värdegrund',
'professionellt',
'human',
'match',
'kul',
'kvalité',

'gemenskap',
'bravur',
'analytisk',
'aktiv',
'struktur',
'design',
'stabil',
'datorvan',
'kraft',

'innovativ',
'avancer',
'komplex',
'stresstå',
'socialt',
'specialiser',
'dialog',
'drivkraft',
'förväntning',
'digitalt',
'utåt',
'ordning',
'initiativtag',
'integritet',
'linkedin',


'representer',
'dynamisk',
'instagram',
'genomsyr',
'perspektiv',
'målsättning',
'eftersträv',
'profession',
'värder',
'innovation',
'plattform',
'kvalitetssäkr',
'nytänk',
'besit',
'hållbart',
'coachning',
'koncept',
'förändr',
'plan',
'detalj',
'ödmjuk',
'företagskultur',
'programmering',
'arbetsklim',
'könsfördelning',
'flexibl',
'gdpr',
'arbetsglädj',
'variation',
'stämning',
'målinrik',
'tävlingsinrik',
'problemlös',
'problemlösning',
'ledord',
'marknadsled',
'konkurrenskraft',
'affärsmäss',
'karriärmöj',
'infrastruktur',

'kontaktyt',
'spel',
'kundbemöt',
'effektivitet',
'server',
'vägled',
'utvecklingsarbet',
'smid',
'framkant',
'pålit',
'analy',
'proaktivt',
'systematisk',
'potential',
'projektledning',
'jämställd',
'målgrupp',
'lösningsfokuser',
'öppen',
'attityd',
'talang',


'strategi',
'resurs',
'ambitiös',
'drömjobb',
'drivn',
'nyfiken',
'management',
'digitalisering',
'individuellt',
'förutsät',
'covid',
'agil',
'expander',
'kompetensföretag',
'vidareutveckl',
'stress',
'familjär',
'skratt',


'kundnöjd',
'förbättringsarbet',
'balan',
'livskvalitet',
'värdefull',
'ordningsam',
'fräsch',
'kommunikationsförmåg',
'överträff',
'hemifrån',
'sammansvets',
'trivsel',
'kreativitet',

'generös',
'kliv',
'inklusiv',
'resultatinrik',
'talent',
'kvalitativ',
'stjärn',

'initiativrik',
'arbetsmoral',
'värdeord',
'kontaktnät',
'karriärsteg',
'prisbelönt',
'account',
'säkerhetsmedvet',
'kvalitetsmedvet',
'expansion',

'samarbetsvil',
'trivsam',
'sammanhållning',
'glimt',

'bankid', 'stjärnsälj',

'servicekänsl',
'innovativt',
'lojal',
'anpassningsbar',
'familjärt',

'relationsskap',
'motivation',
'omställning',
'tålamod',
'rättvis',
'tålmod',
'drömjobbet',
'dediker',
'stjärnsälj',
'kundfokus',
'teamkänsl',
'fartfyllt',
'kompetensbaser',
'empatisk',
'uppstart',
'nyckelroll',
'fartfylld',
'glädjesprid',

'tävlingsinrik',
'passioner',
'arbetsliv',


'bollplank',
'kundfokuser',
'kundvård',
'lösningsinrik',
'kärnvärd',
'återkoppling',
'tävnlingsinrik',
'utåtrik',
'frihet'

     ]

def buzz_bigrams():
     return [
('person', 'egenskap'),
('gör', 'skilln'),
('arbet', 'självständ'),
('god', 'samarbetsförmåg'),
('högt', 'tempo'),
('rätt', 'person'),
('vill', 'utveckl'),
('möj', 'utveckl'),
('stor', 'möj'),
('uppsat', 'mål'),
('eget', 'ansv'),
('nya', 'utmaning'),
('egn', 'initiativ'),
('stort', 'intress'),
('arbet', 'team'),
('person', 'utveckling'),
('lätt', 'samarbet'),
('genuint', 'intress'),
('möj', 'påverk'),

('tar', 'ansv'),
('vill', 'bidr'),
('samarbet', 'andr'),
('utveckl', 'arbet'),
('kund', 'behov'),
('positiv', 'inställning'),
('stort', 'engagemang'),
('kommunikativ', 'förmåg'),
('väx', 'företag'),
('varier', 'arbetsuppgift'),
('tillsamman', 'skap'),
('god', 'servic'),
('engager', 'medarbet'),
('god', 'datorvan'),

('arbet', 'högt'),
('stort', 'ansv'),
('social', 'kompet'),
('god', 'kommunikativ'),
('möj', 'väx'),
('lill', 'extr'),
('lär', 'nya'),
('nå', 'mål'),
('erbjud', 'spänn'),
('del', 'team'),
('högt', 'tak'),
('hel', 'värld'),
('samarbet', 'kolleg'),
('driv', 'arbet'),
('jämn', 'könsfördelning'),
('hos', 'familj'),
('hållb', 'utveckling'),
('teknisk', 'intress'),
('erbjud', 'möj'),
('ser', 'möj'),
('långsikt', 'relation'),

('social', 'medi'),
('snabb', 'väx'),
('ansik', 'utåt'),
('driv', 'utveckling'),
('självständ', 'arbet'),
('fokuser', 'kompet'),
('frihet', 'ansv'),
('lag', 'logistik'),
('öpp', 'fokuser'),
('lös', 'problem'),
('ordning', 'red'),
('god', 'arbetsmiljö'),
('utveckl', 'roll'),
('ta', 'chans'),
('väx', 'utveckl'),
('stort', 'fokus'),
('sök', 'driv'),
('erfaren', 'led'),
('skap', 'förutsättning'),
('håll', 'hög'),

('båd', 'självständ'),
('varier', 'arbet'),
('bygg', 'relation'),
('effektivt', 'sätt'),
('god', 'social'),
('utveckl', 'tillsamman'),
('analytisk', 'förmåg'),
('jobb', 'team'),
('engager', 'kolleg'),
('noggran', 'strukturer'),

('person', 'driv'),
('driv', 'utveckl'),
('ger', 'möj'),
('omväxl', 'arbet'),
('stor', 'frihet'),
('social', 'förmåg'),
('driv', 'person'),

('ständ', 'förbättring'),
('nya', 'människ'),
('brinn', 'intress'),
('god', 'stämning'),
('gemensamm', 'mål'),
('mång', 'kontaktyt'),
('erbjud', 'trygg'),
('digital', 'verktyg'),
('erbjud', 'varier'),
('skap', 'värd'),
('tillsamman', 'gör'),
('mångfald', 'styrk'),
('tillsamman', 'team'),
('sök', 'brinn'),

('team', 'sök'),
('utveckl', 'yrkesroll'),
('gott', 'samarbet'),
('stort', 'plus'),
('ständ', 'utveckl'),
('högt', 'arbetstempo'),
('boll', 'luft'),
('gör', 'karriär'),
('verksam', 'tillsamman'),
('hitt', 'perfek'),
('erbjud', 'attraktiv'),
('steg', 'karriär'),
('tillsamman', 'medarbet'),
('möj', 'utveckling'),
('sök', 'engager'),

('rikt', 'kulturliv'),
('tänk', 'nytt'),
('hög', 'integritet'),
('medarbet', 'triv'),
('kul', 'jobbet'),
('team', 'tillsamman'),
('form', 'framtid'),
('miljard', 'kron'),
('vikt', 'egenskap'),
('strukturer', 'arbetssät'),
('stark', 'meriter'),
('värder', 'högt'),
('bra', 'samarbet'),
('lätt', 'anpass'),
('kompetent', 'kolleg'),
('trygg', 'professionell'),
('erbjud', 'intressant'),
('ansv', 'arbet'),
('engagemang', 'glädj'),


('arbet', 'effektivt'),
('triv', 'jobb'),
('trygg', 'yrkesroll'),
('ständ', 'utveckling'),
('arbet', 'varier'),
('mål', 'kandidat'),
('hög', 'arbetsmoral'),
('praktisk', 'erfaren'),
('intress', 'teknik'),
('stark', 'vilj'),
('ta', 'initiativ'),
('hög', 'kvalité'),
('attraktiv', 'arbetsgiv'),
('expansiv', 'fas'),
('god', 'kommunikationsförmåg'),
('känn', 'bekväm'),
('person', 'engagemang'),
('erbjud', 'stor'),
('bäst', 'servic'),

('arbet', 'kontinuer'),
('stort', 'nätverk'),
('förmåg', 'samarbet'),
('spänn', 'arbet'),
('intress', 'människ'),
('sammansvets', 'team'),
('positiv', 'attityd'),
('spänn', 'utmaning'),
('rätt', 'inställning'),
('arbet', 'hållb'),
('snabbt', 'väx'),
('mång', 'boll'),
('spänn', 'uppdrag'),
('utveckling', 'tillväxt'),
('ges', 'möj'),
('marknadsmäss', 'lön'),
('hitt', 'drömjobb'),
('kunder', 'behov'),
('jobb', 'självständ'),
('trygg', 'stabil'),
('person', 'noggran'),
('social', 'person'),
('fortsät', 'utveckl'),
('gill', 'utmaning'),
('möj', 'flexibilitet'),


('känsl', 'servic'),
('rätt', 'förutsättning'),
('självständ', 'team'),
('könsfördelning', 'ser'),
('brett', 'utbud'),


('noggran', 'arbet'),
('positiv', 'engager'),
('erbjud', 'stimuler'),
('värdesät', 'kvalitet'),
('hjälp', 'utveckl'),
('triv', 'bra'),
('balan', 'arbet'),
('såväl', 'självständ'),

('utman', 'tjänst'),
('hög', 'ambition'),
('självständ', 'driv'),
('glad', 'positiv'),
('vilj', 'utveckl'),
('maximer', 'ersättning'),
('bäst', 'villkor'),
('flexibilitet', 'måst'),
('skap', 'relation'),
('team', 'arbet'),
('kontak', 'ansvar'),
('gott', 'arbetsklim'),
('egn', 'beslut'),

('trygg', 'person'),
('lil', 'extr'),
('bra', 'tempo'),

('social', 'utåtrik'),

('stimuler', 'arbet'),

('glimt', 'ögat'),
('klättr', 'karriärsteg'),
('redo', 'utveckl'),

('socialt', 'begåv'),
('strukturer', 'noggran'),
('driv', 'ansvarsfull'),
('praktisk', 'lagd'),
('stort', 'driv'),

('värld', 'bäst'),
('hög', 'servicenivå'),
('engager', 'driv'),

('kul', 'tillsamman'),
('driv', 'engager'),
('noggran', 'positiv'),
('utåtrik', 'person'),
('lagspel', 'god'),
('engagemang', 'driv'),
('gill', 'högt'),
('del', 'teamet'),
('väx', 'knak'),
('inställning', 'engagemang'),
('utveckl', 'person'),

('tävlingsinrik', 'driv'),
('drivn', 'medarbet'),
('stark', 'engagemang'),

('spänn', 'projek'),
('social', 'drivn'),
('social', 'engager'),
('jobb', 'problemlösning'),
('bra', 'sammanhållning')

     ]