def excluded_monograms():
     return [
'arbet',
'sök',
'komm',
'person',
'samt',
'tjänst',
'erfaren',
'kund',
'god',
'vill',
'hos',
'möj',
'jobb',
'erbjud',
'ansökan',
'vikt',
'roll',
'utveckl',
'även',
'ser',
'båd',
'medarbet',
'arbetsuppgift',
'del',
'gör',
'tillsamman',
'ska',
'se',
'finn',
'verksam',
'får',
'stor',
'olik',
'svensk',
'dag',
'tid',
'kunskap',
'gärn',
'utbildning',
'skap',
'mer',
'sver',
'in',
'arbetet',
'andr',
'meriter',
'hjälp',
'löp',
'nya',
'genom',
'välkomm',
'samarbet',
'uppdrag',
'led',
'bra',
'ta',
'kolleg',
'behöv',
'utveckling',
'innebär',
'hel',
'krav',
'också',
'enl',
'kontak',
'tal',
'därför',
'företag',
'via',
'www',
'trygg',
'kunn',
'förmåg',
'ansvar',
'servic',
'sätt',
'triv',
'kommun',
'idag',
'fler',
'rätt',
'bäst',
'övr',
'företaget',
'behov',
'barn',
'få',
'rekrytering',
'ansv',
'människ',
'anställning',
'tar',
'skrift',
'stort',
'bidr',
'hög',
'sker',
'lär',


'när',
'anställd',
'kompet',
'sälj',
'år',
'start',
'intress',
'mål',
'körkort',
'skick',
'sjukskötersk',
'arbetstid',
'kräv',
'ingår',
'bygg',
'emot',
'personal',
'https',
'vård',
'lägg',
'försäljning',
'läs',
'följ',
'patient',
'elev',
'information',
'alltid',
'stockholm',
'mång',
'känn',
'varier',
'ann',
'hitt',
'urval',
'redan',
'heltid',
'störst',
'intervju',
'kvalitet',
'vid',
'bland',
'teknisk',
'engelsk',
'ge',
'it',
'års',
'spänn',
'förutsättning',
'egenskap',
'stark',
'såväl',
'gill',
'tror',
'framtid',
'produk',
'b',
'utifrån',
'utför',
'lön',
'fråg',
'arbetsplat',
'vardag',
'samtid',
'kvalifikation',
'minst',
'miljö',
'tyck',
'hanter',
'van',
'organisation',
'pass',
'jobbet',
'innan',
'möt',
'ansök',
'uppgift',
'konsult',
'högt',
'stöd',
'fram',
'bemanning',
'överenskomm',
'region',
'lyck',
'ab',
'avdelning',
'ger',
'lösning',
'strukturer',
'egn',
'kollektivavtal',


'sist',
'profil',
'projek',
'använd',
'just',
'planer',
'ca',
'varmt',
'bransch',
'genomför',
'arbetsgiv',
'relation',
'leverer',
'lätt',
'teknik',
'håll',
'eget',
'ligg',
'tillsät',
'gäll',
'sen',
'förekomm',
'består',
'rekryteringsprocess',
'res',
'uppdraget',
'intresser',
'två',
'egen',
'går',
'rol',
'annan',
'ansökning',
'grund',
'grupp',
'lokal',
'process',
'omgåend',
'främst',
'system',
'familj',
'vet',
'butik',
'göteborg',
'likn',
'cv',
'väl',
'tyd',
'digital',
'plat',
'skilln',
'ständ',
'enhet',
'relevant',
'lämp',
'e',
'tillgång',
'assistent',
'karriär',
'runt',
'kommunikation',
'form',
'nå',
'rekryter',
'kont',
'inför',
'veck',
'bakgrund',
'lag',
'allakando',
'huvudsak',
'undanb',
'värld',
'fast',
'ansökningsdag',
'områd',
'arbetsplats',
'utbild',
'tillträd',
'rekryteringsföretag',
'a',
'sjukvård',
'säkerställ',
'result',
'förstå',
'bättr',
'extr',
'först',
'bil',
'fördel',
'cirk',
'besök',
'tillämp',
'förmån',
'hemsid',


'arbetssät',
'bolag',
'gott',
'mån',
'skol',
'ytter',
'all',
'kort',
'långsikt',
'aktivt',
'helg',
'stött',
'chef',
'hand',
'ställ',
'direk',
'pedagogisk',
'framåt',
'varandr',
'sitt',
'viss',
'mod',
'lång',
'påverk',
'motsvar',
'kväll',
'välkomn',
'enkelt',
'skolan',
'verk',
'omfattning',
'omfat',
'beslut',
'bemöt',
'produktion',
'läxhjälp',
'hälso',
'ny',
'kring',
'sträv',
'tillgäng',
'brev',
'lit',
'ekonomi',
'behärsk',
'västr',
'friskvårdsbidrag',
'aktivitet',
'snabbt',
'bedriv',
'skriv',
'administration',
'ute',
'ort',
'lik',
'värdesät',
'liv',
'snart',
'rikt',
'legitimer',
'utöv',
'hr',
'skån',
'vän',
'måst',
'förbättr',
'näst',
'låt',
'eftersom',
'vilj',
'stad',
'störr',
'här',
'bemanningsföretag',
'com',
'mest',
'tillsvidareanställning',
'dessutom',
'natur',
'aktör',
'underhåll',
'assistan',
'kontinuer',
'marknad',
'per',
'förvaltning',
'boend',
'individ',


'språket',
'malmö',
'delt',
'ske',
'januari',
'tänk',
'månad',
'kultur',
'industri',
'flyt',
'serviceinrik',
'bolaget',
'snabb',
'intressant',
'utdrag',
'funger',
'förskol',
'vis',
'individuell',
'inriktning',
'problem',
'oavset',
'undervisning',
'inget',
'erf',
'ur',
'såsom',
'gå',
'introduktion',
'ext',
'tre',
'annons',
'end',
'exempelvis',
'innefat',
'belastningsregistret',
'timm',
'bör',
'telefon',
'leverantör',
'nytt',
'önsk',
'förvänt',
'vision',
'offent',
'förmågan',
'området',
'omsorg',
'öpp',
'int',
'landet',
'trev',
'polis',
'helt',
'välj',
'dagtid',
'mail',
'provanställning',
'självklart',
'planering',
'häls',
'central',
'verktyg',
'öppn',
'kompetent',
'sak',
'arbetslivserfaren',
't',
'livet',
'attraktiv',
'ingå',
'situation',
'länk',
'and',
'bor',
'tillhör',
'typ',
'professionell',
'uppsat',
'snar',
'auktoriser',
'börj',
'ex',
'fysisk',
'väg',
'skall',
'gemensamm',


'avtal',
'uppsal',
'prioriter',
'försälj',
'barnvak',
'vårdcentral',
'veckan',
'ungdom',
'samband',
'topwork',
'önskemål',
'underskötersk',
'framgång',
'placering',
'drift',
'står',
'prägl',
'chans',
'gäst',
'logistik',
'sjukhus',
'bestämt',
'dokumenter',
'förändring',
'administrativ',
'kontaktperson',
'mat',
'läk',
'väld',
'deltid',
'nivå',
'c',
'specialist',
'kansk',
'nord',
'exempel',
'gång',
'kandidat',
'län',
'studi',
'klinik',
'uppföljning',
'restaurang',
'hem',
'lös',
's',
'lev',
'för',
'förlag',
'befint',
'förhållningssät',
'bruk',
'steg',
'ager',
'uttryck',
'marknadsföring',
'svar',
'självklar',
'hör',
'villk',
'betyd',
'medicinsk',
'styr',
'support',
'internationell',
'bar',
'högst',
'rör',
'måndag',
'fredag',
'maskin',
'inköp',
'anläggning',
'el',
'varumärk',
'm',
'värd',
'http',
'var',


'rutin',
'försäkring',
'mindr',
'träff',
'nöjd',
'koncern',
'innehåll',
'antal',
'anställningsform',
'dokumentation',
'registrer',
'test',
'fortsät',
'året',
'idé',
'uppskat',
'bifog',
'stödj',
'oft',
'mynd',
'ansökningstid',
'tak',
'konsultchef',
'omväxl',
'invån',
'götalandsregion',
'eventuell',
'alternativt',
'mottagning',
'klick',
'utgår',
'extrajobb',
'hjärt',
'arbetsbeskrivning',
'nanny',
'kunder',
'lämn',
'funktion',
'likvärd',
'affär',
'yrkesroll',
'språk',
'upplev',
'utanför',
'schem',
'samhället',
'post',
'kundservic',
'jönköping',
'hopp',
'centrum',
'projektled',
'internt',
'partn',
'bedöm',
'ärend',
'förutom',
'plus',
'bemlo',
'grundlägg',
'insats',
'säker',
'provision',
'händ',
'norg',
'sköt',
'period',
'ihop',
'uppnå',
'fyr',
'perfek',
'dat',
'samtal',
'människor',
'tillsvid',
'direktkontak',
'vänt',
'ekonomisk',
'rapporter',
'handl',

     ]

def excluded_bigrams():
        return [
               ('tal', 'skrift'),
('välkomm', 'ansökan'),
('stor', 'vikt'),
('god', 'kunskap'),
('ser', 'gärn'),
('in', 'ansökan'),
('erfaren', 'arbet'),
('bland', 'ann'),
('redan', 'idag'),
('hos', 'kund'),
('tid', 'erfaren'),
('komm', 'arbet'),
('sker', 'löp'),
('enl', 'överenskomm'),
('års', 'erfaren'),
('varmt', 'välkomm'),
('skick', 'in'),
('b', 'körkort'),
('läs', 'mer'),
('svensk', 'engelsk'),
('vikt', 'person'),
('https', 'www'),
('lägg', 'stor'),
('sök', 'tjänst'),
('sist', 'ansökningsdag'),
('vill', 'arbet'),
('tjänst', 'komm'),
('person', 'lämp'),
('båd', 'tal'),
('ansökan', 'redan'),
('kunskap', 'svensk'),
('fram', 'emot'),
('ser', 'fram'),
('sök', 'vill'),
('komm', 'tillsät'),
('tillsät', 'innan'),
('jobb', 'hos'),
('när', 'samarbet'),
('meriter', 'erfaren'),
('kvalifikation', 'sök'),
('innan', 'sist'),
('hos', 'får'),
('god', 'förmåg'),
('hälso', 'sjukvård'),
('person', 'brev'),
('snart', 'möj'),
('löp', 'tjänst'),
('vill', 'jobb'),
('får', 'möj'),
('person', 'assistent'),
('lyck', 'roll'),
('arbet', 'tillsamman'),
('svensk', 'språket'),
('sver', 'störst'),
('vikt', 'del'),
('emot', 'ansökning'),
('intervju', 'sker'),
('möj', 'arbet'),
('löp', 'urval'),
('urval', 'intervju'),
('ansökning', 'via'),
('känn', 'trygg'),
('behärsk', 'svensk'),
('bemanning', 'rekryteringsföretag'),
('svensk', 'tal'),
('mer', 'information'),
('utdrag', 'ur'),
('emot', 'ansökan'),
('t', 'ex'),
('komm', 'få'),
('ska', 'kunn'),
('tar', 'emot'),
('komm', 'även'),
('anställning', 'hos'),
('hel', 'sver'),
('arbetsuppgift', 'komm'),
('västr', 'götalandsregion'),
('urval', 'sker'),
('triv', 'arbet'),
('minst', 'års'),
('start', 'omgåend'),
('arbet', 'hos'),


('allakando', 'läxhjälp'),
('god', 'möj'),
('komm', 'ske'),
('inget', 'krav'),
('vet', 'mer'),
('lägg', 'person'),
('tillsamman', 'kolleg'),
('vill', 'gör'),
('hjälp', 'kund'),
('vill', 'del'),
('stor', 'del'),
('cv', 'person'),
('arbet', 'båd'),
('vän', 'bestämt'),
('komm', 'ingå'),
('konsult', 'hos'),
('skap', 'god'),
('omfattning', 'heltid'),
('övr', 'information'),
('vill', 'vet'),
('svensk', 'båd'),
('huvudsak', 'arbetsuppgift'),
('komm', 'lägg'),
('legitimer', 'sjukskötersk'),
('fler', 'olik'),
('tillträd', 'enl'),
('van', 'arbet'),
('måndag', 'fredag'),
('hitt', 'rätt'),
('hög', 'kvalitet'),
('dag', 'kväll'),
('direktkontak', 'bemanning'),
('ta', 'emot'),
('tid', 'arbet'),
('cirk', 'medarbet'),
('ske', 'löp'),
('arbetet', 'innebär'),
('samt', 'god'),
('rekryteringsföretag', 'samt'),
('nya', 'medarbet'),
('ansökan', 'via'),
('http', 'www'),
('utbildning', 'erfaren'),
('barn', 'ungdom'),
('undanb', 'vän'),
('finn', 'möj'),
('körkort', 'krav'),
('bäst', 'möj'),
('sök', 'legitimer'),
('triv', 'roll'),
('bemanning', 'rekrytering'),
('lång', 'erfaren'),
('dag', 'arbet'),
('flyt', 'svensk'),
('vikt', 'lägg'),
('engelsk', 'tal'),
('e', 'post'),
('intervju', 'komm'),
('erfaren', 'likn'),
('tjänst', 'sök'),
('ta', 'egn'),
('utveckl', 'verksam'),
('arbet', 'aktivt'),
('roll', 'komm'),
('kunskap', 'erfaren'),
('finn', 'god'),
('ur', 'belastningsregistret'),
('ansökan', 'snart'),
('god', 'relation'),
('bl', 'a'),
('tjänst', 'innebär'),
('olik', 'typ'),
('arbet', 'när'),
('ta', 'ansv'),
('individuell', 'lönesättning'),
('kväll', 'helg'),
('ute', 'hos'),
('tjänst', 'tillsät'),
('just', 'sök'),
('sök', 'nya'),
('körkort', 'tillgång'),
('ingår', 'även'),
('via', 'mail'),
('ska', 'känn'),
('gärn', 'erfaren'),
('skick', 'ansökan'),
('uppdrag', 'hos'),
('anställd', 'hos'),
('triv', 'hos'),
('ytter', 'jobbannons'),
('olik', 'bakgrund'),
('ta', 'fram'),


('näst', 'steg'),
('hos', 'komm'),
('mer', 'www'),
('vård', 'omsorg'),
('erfaren', 'försäljning'),
('arbet', 'utifrån'),
('sök', 'sök'),
('tal', 'skriv'),
('arbet', 'barn'),
('tillsamman', 'andr'),
('dygnet', 'runt'),
('dag', 'arbetet'),
('pass', 'in'),
('kunn', 'arbet'),
('person', 'assistan'),
('arbet', 'person'),
('arbet', 'löp'),
('komm', 'jobb'),
('sver', 'led'),
('arbetsuppgift', 'roll'),
('andr', 'människ'),
('körkort', 'b'),
('tagit', 'ställning'),
('profil', 'sök'),
('lön', 'enl'),
('bestämt', 'direktkontak'),
('sen', 'januari'),
('se', 'jobb'),
('meriter', 'tid'),
('månader', 'provanställning'),
('tillgång', 'bil'),
('kund', 'finn'),
('gärn', 'in'),
('undanb', 'därför'),
('ställning', 'rekryteringskanal'),
('tyck', 'arbet'),
('sist', 'ansökningsdatum'),
('enl', 'kollektivavtal'),
('får', 'arbet'),
('försälj', 'ytter'),
('god', 'kommunikation'),
('går', 'igenom'),
('hel', 'landet'),
('genom', 'klick'),
('arbetsuppgift', 'ingår'),
('eftergymnasial', 'utbildning'),
('låt', 'intressant'),
('innan', 'ansökningstid'),
('sver', 'norg'),
('via', 'telefon'),
('uttryck', 'väl'),
('via', 'e'),
('per', 'veck'),
('arbetstid', 'förlag'),
('via', 'länk'),
('sök', 'fler'),
('region', 'skån'),
('bäst', 'förutsättning'),
('tjänst', 'tillsvidareanställning'),
('annonsering', 'rekryteringshjälp'),
('finn', 'även'),
('därför', 'vikt'),
('hög', 'krav'),
('mång', 'olik'),
('ska', 'få'),
('västr', 'götaland'),
('person', 'vill'),
('vikt', 'komm'),
('tjänst', 'heltid'),
('hemsid', 'www'),
('www', 'allakando'),
('allakando', 'se'),
('därför', 'sök'),
('rekrytering', 'sker'),
('academic', 'work'),
('gill', 'arbet'),
('minst', 'år'),
('sök', 'erfaren'),
('samt', 'andr'),
('medarbet', 'vikt'),
('få', 'möj'),
('vikt', 'roll'),
('välkomm', 'sök'),
('först', 'hand'),
('hos', 'topwork'),
('komm', 'anställd'),


('ca', 'medarbet'),
('gärn', 'mer'),
('även', 'arbet'),
('jönköping', 'län'),
('ansök', 'redan'),
('ska', 'triv'),
('se', 'laxhjalp'),
('god', 'utvecklingsmöj'),
('nya', 'kolleg'),
('rekryteringskanal', 'marknadsföring'),
('sök', 'jobbet'),
('intervju', 'löp'),
('bemanning', 'förmedling'),
('förmedling', 'rekryteringsföretag'),
('rekryteringsföretag', 'försälj'),
('läs', 'gärn'),
('tar', 'end'),
('samt', 'arbet'),
('sök', 'person'),
('inför', 'rekryteringsarbetet'),
('båd', 'kund'),
('hel', 'tid'),
('krav', 'tjänst'),
('gärn', 'sök'),
('komm', 'in'),
('dag', 'veckan'),
('bäst', 'sätt'),
('samt', 'försälj'),
('krav', 'körkort'),
('välkomm', 'kontak'),
('sök', 'därför'),
('ta', 'hand'),
('erbjud', 'annonsering'),
('hos', 'erbjud'),
('tjänst', 'kräv'),
('välkomn', 'sök'),
('försälj', 'undanb'),
('erbjud', 'god'),
('hos', 'finn'),
('komm', 'kontak'),
('del', 'arbetet'),
('förmåg', 'arbet'),
('innebär', 'komm'),
('tillsamman', 'arbet'),
('roll', 'ser'),
('via', 'hemsid'),
('tillämp', 'löp'),
('sök', 'olik'),
('bifog', 'cv'),
('polis', 'se'),
('ansökan', 'sen'),
('medarbet', 'arbet'),
('behöv', 'hjälp'),
('arbetet', 'kräv'),
('bedöm', 'likvärd'),
('information', 'start'),
('arbetet', 'sker'),
('rekrytering', 'bemanningsföretag'),
('såväl', 'tal'),
('möj', 'få'),
('båd', 'svensk'),
('komm', 'också'),
('ta', 'del'),
('rekryteringssajt', 'likn'),
('ställ', 'krav'),
('ställ', 'hög'),
('gör', 'löp'),
('ansökan', 'snar'),
('arbet', 'olik'),
('int', 'ext'),
('nöjd', 'kund'),
('vill', 'skap'),
('information', 'tjänst'),
('auktoriser', 'bemanningsföretag'),
('kontak', 'mediesälj'),
('jobb', 'tillsamman'),
('kontak', 'kund'),
('sök', 'just'),
('nya', 'sak'),


('vill', 'ge'),
('skick', 'gärn'),
('löp', 'skick'),
('engelsk', 'båd'),
('vill', 'ta'),
('arbet', 'dag'),
('sver', 'bäst'),
('internt', 'externt'),
('end', 'emot'),
('komm', 'ansvar'),
('gott', 'bemöt'),
('kund', 'sök'),
('obehindr', 'svensk'),
('ansökningstid', 'gått'),
('innan', 'anställning'),
('andr', 'lik'),
('direk', 'hos'),
('kund', 'komm'),
('ansökan', 'välkomm'),
('kund', 'konsult'),
('kompet', 'övr'),
('olik', 'bransch'),
('anpass', 'roll'),
('även', 'möj'),
('bestämt', 'kontak'),
('öppn', 'anpass'),
('roll', 'arbetsplats'),
('urvalet', 'löp'),
('övr', 'förutsättning'),
('erbjud', 'tjänst'),
('förutsättning', 'öppn'),
('arbetsplats', 'behov'),
('arbet', 'även'),
('sök', 'jobb'),
('mediesälj', 'rekryteringssajt'),
('samtid', 'enkelt'),
('igenom', 'urvalet'),
('huvudsak', 'sysselsättning'),
('polis', 'belastningsregist'),
('arbet', 'god'),
('kontak', 'kontaktperson'),
('e', 'handel'),
('språket', 'båd'),
('hemm', 'hos'),
('skrift', 'meriter'),
('m', 'm'),
('rekrytering', 'samarbet'),
('skrift', 'svensk'),
('it', 'teknik'),
('arbetsuppgift', 'sök'),
('sätt', 'in'),
('nå', 'uppsat'),
('stort', 'eget'),
('erbjud', 'erbjud'),
('roll', 'innebär'),
('ge', 'kund'),
('rekryter', 'löp'),
('arbet', 'hel'),
('tillsamman', 'övr'),
('kund', 'kolleg'),
('behöv', 'kunn'),
('hos', 'arbet'),
('högst', 'kvalitet'),
('dokumenter', 'erfaren'),
('sjukskötersk', 'uppdrag'),
('start', 'enl'),
('ta', 'näst'),
('relevant', 'utbildning'),
('erfaren', 'kunskap'),
('person', 'gill'),
('tvek', 'skick'),
('innebär', 'arbet'),
('sätt', 'kund'),
('trygg', 'anställning'),
('förmåg', 'skap'),
('ca', 'anställd'),
('van', 'förekomm'),
('arbetstid', 'varier'),
('region', 'jönköping'),
('erfaren', 'utbildning'),


('del', 'arbet'),
('arbetsuppgift', 'varier'),
('ser', 'helst'),
('egen', 'bil'),
('skap', 'förtroend'),
('arbet', 'människ'),
('arbet', 'bemanning'),
('skap', 'bäst'),
('komm', 'tillhör'),
('ansökan', 'ska'),
('rätt', 'medarbet'),
('medarbet', 'ska'),
('ser', 'också'),
('undanb', 'erbjud'),
('hjälp', 'människ'),
('arbet', 'ständ'),
('god', 'fysik'),
('gill', 'jobb'),
('kund', 'arbet'),
('gör', 'genom'),
('person', 'sök'),
('välkomm', 'in'),
('god', 'förutsättning'),
('tjänst', 'tjänst'),
('också', 'vikt'),
('annan', 'huvudsak'),
('få', 'bäst'),
('kunskap', 'engelsk'),
('dag', 'andr'),
('rekryteringshjälp', 'samband'),
('möj', 'jobb'),
('person', 'god'),
('komm', 'del'),
('arbet', 'konsult'),
('https', 'polis'),
('barn', 'ung'),
('skilln', 'dag'),
('tjänst', 'ingår'),
('arbetet', 'ingår'),
('tack', 'var'),
('ser', 'meriter'),
('sök', 'sjukskötersk'),
('ansökan', 'västr'),
('person', 'ser'),
('minst', 'två'),
('intresser', 'arbet'),
('kräv', 'god'),
('kund', 'fokus'),
('tar', 'gärn'),
('ska', 'sök'),
('runt', 'landet'),
('heltid', 'deltid'),
('förekomm', 'arbetsuppgift'),
('sök', 'erf'),
('led', 'jobb'),
('skrift', 'god'),
('meriter', 'kunskap'),
('arbet', 'utveckl'),
('arbet', 'komm'),
('meriter', 'tjänst'),
('väl', 'tal'),
('ext', 'aktör'),
('medarbet', 'nya'),
('sälj', 'hos'),
('erfaren', 'person'),
('kolleg', 'arbet'),
('befint', 'kund'),
('må', 'bra'),
('för', 'sist'),
('arbet', 'strukturer'),
('likn', 'arbetsuppgift'),
('ansök', 'via'),
('oavset', 'sök'),
('aktuell', 'tjänst'),
('vill', 'ska'),
('finn', 'tillgäng'),
('erbjud', 'kund'),
('rol', 'extrajobb'),
('möt', 'kund'),
('kund', 'bäst'),
('samt', 'erfaren'),
('ingår', 'också'),
('erbjud', 'även'),


('ge', 'god'),
('möj', 'förlängning'),
('hjälp', 'elev'),
('lär', 'känn'),
('planer', 'genomför'),
('bra', 'jobb'),
('ser', 'även'),
('partn', 'oavset'),
('idag', 'tjänst'),
('in', 'roll'),
('god', 'förstå'),
('utmaning', 'topwork'),
('enl', 'iso'),
('nya', 'kund'),
('förmåg', 'uttryck'),
('kunn', 'ta'),
('skap', 'trygg'),
('därför', 'erbjud'),
('tillsvidareanställning', 'heltid'),
('mån', 'fre'),
('vikt', 'god'),
('ser', 'självklar'),
('början', 'karriär'),
('ur', 'polis'),
('komm', 'triv'),
('god', 'result'),
('tillgång', 'egen'),
('registrer', 'ansökan'),
('emot', 'hör'),
('kund', 'räkning'),
('arbet', 'bra'),
('meriter', 'inget'),
('kväll', 'natt'),
('får', 'ta'),
('dag', 'verksam'),
('möj', 'sök'),
('bok', 'in'),
('fokus', 'ligg'),
('se', 'https'),
('relation', 'kund'),
('helt', 'enkelt'),
('sker', 'enl'),
('kort', 'beslutsväg'),
('kund', 'ska'),
('arbetsgiv', 'bedöm'),
('barnvak', 'hos'),
('ansökan', 'skick'),
('består', 'idag'),
('tillträd', 'omgåend'),
('utannonser', 'tjänst'),
('genom', 'hel'),
('båd', 'internt'),
('produk', 'tjänst'),
('marknadsföring', 'undanb'),
('via', 'www'),
('uppdraget', 'start'),
('patient', 'fokus'),
('vill', 'få'),
('hög', 'kompet'),
('stark', 'varumärk'),
('norg', 'danmark'),
('tillsät', 'tjänst'),
('sök', 'tid'),
('få', 'arbet'),
('års', 'arbetslivserfaren'),
('bygg', 'administration'),
('vid', 'ser'),
('meriter', 'arbet'),
('vänt', 'ansökan'),
('tror', 'sök'),
('ge', 'bäst'),
('sök', 'arbet'),
('fatt', 'beslut'),
('rol', 'jobbet'),
('hos', 'fler'),
('därför', 'bestämt'),
('forskning', 'utbildning'),
('sök', 'utbild'),
('barn', 'år'),
('fler', 'års'),
('led', 'utveckl'),
('komm', 'gör'),
('språk', 'meriter'),
('bakgrund', 'erfaren'),
('begär', 'utdrag'),
('egenskap', 'sök'),
('behöv', 'god'),
('fråg', 'utannonser'),
('gärn', 'tid'),
('likn', 'arbet'),
('tar', 'hand'),
('fråg', 'tjänst'),
('kort', 'varsel'),



        ]
