def excluded_monograms():
     return [
'n',
'arbet',
'sök',
'komm',
'person',
'samt',
'tjänst',
'erfaren',
'kund',
'god',
'vill',
'hos',
'möj',
'jobb',
'erbjud',
'ansökan',
'vikt',
'roll',
'utveckl',
'även',
'ser',
'båd',
'medarbet',
'arbetsuppgift',
'del',
'gör',
'tillsamman',
'ska',
'se',
'finn',
'verksam',
'får',
'stor',
'olik',
'svensk',
'dag',
'tid',
'kunskap',
'gärn',
'utbildning',
'skap',
'mer',
'sver',
'in',
'arbetet',
'andr',
'meriter',
'hjälp',
'löp',
'nya',
'genom',
'välkomm',
'samarbet',
'uppdrag',
'led',
'bra',
'ta',
'kolleg',
'behöv',
'utveckling',
'innebär',
'hel',
'krav',
'också',
'enl',
'kontak',
'tal',
'därför',
'företag',
'via',
'www',
'trygg',
'kunn',
'förmåg',
'ansvar',
'servic',
'sätt',
'triv',
'kommun',
'idag',
'fler',
'rätt',
'bäst',
'övr',
'företaget',
'behov',
'barn',
'få',
'rekrytering',
'ansv',
'människ',
'anställning',
'tar',
'skrift',
'stort',
'bidr',
'hög',
'sker',
'lär',


'när',
'anställd',
'kompet',
'sälj',
'år',
'start',
'intress',
'mål',
'körkort',
'skick',
'sjukskötersk',
'arbetstid',
'kräv',
'ingår',
'bygg',
'emot',
'personal',
'https',
'vård',
'lägg',
'försäljning',
'läs',
'följ',
'patient',
'elev',
'information',
'alltid',
'stockholm',
'mång',
'känn',
'varier',
'ann',
'hitt',
'urval',
'redan',
'heltid',
'störst',
'intervju',
'kvalitet',
'vid',
'bland',
'teknisk',
'engelsk',
'ge',
'it',
'års',
'spänn',
'förutsättning',
'egenskap',
'stark',
'såväl',
'gill',
'tror',
'framtid',
'produk',
'b',
'utifrån',
'utför',
'lön',
'fråg',
'arbetsplat',
'vardag',
'samtid',
'kvalifikation',
'minst',
'miljö',
'tyck',
'hanter',
'van',
'organisation',
'pass',
'jobbet',
'innan',
'möt',
'ansök',
'uppgift',
'konsult',
'högt',
'stöd',
'fram',
'bemanning',
'överenskomm',
'region',
'lyck',
'ab',
'avdelning',
'ger',
'lösning',
'strukturer',
'egn',
'kollektivavtal',


'sist',
'profil',
'projek',
'använd',
'just',
'planer',
'ca',
'varmt',
'bransch',
'genomför',
'arbetsgiv',
'relation',
'leverer',
'lätt',
'teknik',
'håll',
'eget',
'ligg',
'tillsät',
'gäll',
'sen',
'förekomm',
'består',
'rekryteringsprocess',
'res',
'uppdraget',
'intresser',
'två',
'egen',
'går',
'rol',
'annan',
'ansökning',
'grund',
'grupp',
'lokal',
'process',
'omgåend',
'främst',
'system',
'familj',
'vet',
'butik',
'göteborg',
'likn',
'cv',
'väl',
'tyd',
'digital',
'plat',
'skilln',
'ständ',
'enhet',
'relevant',
'lämp',
'e',
'tillgång',
'assistent',
'karriär',
'runt',
'kommunikation',
'form',
'nå',
'rekryter',
'kont',
'inför',
'veck',
'bakgrund',
'lag',
'allakando',
'huvudsak',
'undanb',
'värld',
'fast',
'ansökningsdag',
'områd',
'arbetsplats',
'utbild',
'tillträd',
'rekryteringsföretag',
'a',
'sjukvård',
'säkerställ',
'result',
'förstå',
'bättr',
'extr',
'först',
'bil',
'fördel',
'cirk',
'besök',
'tillämp',
'förmån',
'hemsid',


'arbetssät',
'bolag',
'gott',
'mån',
'skol',
'ytter',
'all',
'kort',
'långsikt',
'aktivt',
'helg',
'stött',
'chef',
'hand',
'ställ',
'direk',
'pedagogisk',
'framåt',
'varandr',
'sitt',
'viss',
'mod',
'lång',
'påverk',
'motsvar',
'kväll',
'välkomn',
'enkelt',
'skolan',
'verk',
'omfattning',
'omfat',
'beslut',
'bemöt',
'produktion',
'läxhjälp',
'hälso',
'ny',
'kring',
'sträv',
'tillgäng',
'brev',
'lit',
'ekonomi',
'behärsk',
'västr',
'friskvårdsbidrag',
'aktivitet',
'snabbt',
'bedriv',
'skriv',
'administration',
'ute',
'ort',
'lik',
'värdesät',
'liv',
'snart',
'rikt',
'legitimer',
'utöv',
'hr',
'skån',
'vän',
'måst',
'förbättr',
'näst',
'låt',
'eftersom',
'vilj',
'stad',
'störr',
'här',
'bemanningsföretag',
'com',
'mest',
'tillsvidareanställning',
'dessutom',
'natur',
'aktör',
'underhåll',
'assistan',
'kontinuer',
'marknad',
'per',
'förvaltning',
'boend',
'individ',


'språket',
'malmö',
'delt',
'ske',
'januari',
'tänk',
'månad',
'kultur',
'industri',
'flyt',
'serviceinrik',
'bolaget',
'snabb',
'intressant',
'utdrag',
'funger',
'förskol',
'vis',
'individuell',
'inriktning',
'problem',
'oavset',
'undervisning',
'inget',
'erf',
'ur',
'såsom',
'gå',
'introduktion',
'ext',
'tre',
'annons',
'end',
'exempelvis',
'innefat',
'belastningsregistret',
'timm',
'bör',
'telefon',
'leverantör',
'nytt',
'önsk',
'förvänt',
'vision',
'offent',
'förmågan',
'området',
'omsorg',
'öpp',
'int',
'landet',
'trev',
'polis',
'helt',
'välj',
'dagtid',
'mail',
'provanställning',
'självklart',
'planering',
'häls',
'central',
'verktyg',
'öppn',
'kompetent',
'sak',
'arbetslivserfaren',
't',
'livet',
'attraktiv',
'ingå',
'situation',
'länk',
'and',
'bor',
'tillhör',
'typ',
'professionell',
'uppsat',
'snar',
'auktoriser',
'börj',
'ex',
'fysisk',
'väg',
'skall',
'gemensamm',


'avtal',
'uppsal',
'prioriter',
'försälj',
'barnvak',
'vårdcentral',
'veckan',
'ungdom',
'samband',
'topwork',
'önskemål',
'underskötersk',
'framgång',
'placering',
'drift',
'står',
'prägl',
'chans',
'gäst',
'logistik',
'sjukhus',
'bestämt',
'dokumenter',
'förändring',
'administrativ',
'kontaktperson',
'mat',
'läk',
'väld',
'deltid',
'nivå',
'c',
'specialist',
'kansk',
'nord',
'exempel',
'gång',
'kandidat',
'län',
'studi',
'klinik',
'uppföljning',
'restaurang',
'hem',
'lös',
's',
'lev',
'för',
'förlag',
'befint',
'förhållningssät',
'bruk',
'steg',
'ager',
'uttryck',
'marknadsföring',
'svar',
'självklar',
'hör',
'villk',
'betyd',
'medicinsk',
'styr',
'support',
'internationell',
'bar',
'högst',
'rör',
'måndag',
'fredag',
'maskin',
'inköp',
'anläggning',
'el',
'varumärk',
'm',
'värd',
'http',
'var',


'rutin',
'försäkring',
'mindr',
'träff',
'nöjd',
'koncern',
'innehåll',
'antal',
'anställningsform',
'dokumentation',
'registrer',
'test',
'fortsät',
'året',
'idé',
'uppskat',
'bifog',
'stödj',
'oft',
'mynd',
'ansökningstid',
'tak',
'konsultchef',
'omväxl',
'invån',
'götalandsregion',
'eventuell',
'alternativt',
'mottagning',
'klick',
'utgår',
'extrajobb',
'hjärt',
'arbetsbeskrivning',
'nanny',
'kunder',
'lämn',
'funktion',
'likvärd',
'affär',
'yrkesroll',
'språk',
'upplev',
'utanför',
'schem',
'samhället',
'post',
'kundservic',
'jönköping',
'hopp',
'centrum',
'projektled',
'internt',
'partn',
'bedöm',
'ärend',
'förutom',
'plus',
'bemlo',
'grundlägg',
'insats',
'säker',
'provision',
'händ',
'norg',
'sköt',
'period',
'ihop',
'uppnå',
'fyr',
'perfek',
'dat',
'samtal',
'människor',
'tillsvid',
'direktkontak',
'vänt',
'ekonomisk',
'rapporter',
'handl',


'handledning',
'dygnet',
'världsklass',
'ung',
'förstår',
'klar',
'universitet',
'fortsat',
'natt',
'let',
'merit',
'kombiner',
'början',
'redo',
'stärk',
'befin',
'inkluder',
'privat',
'gått',
'beroend',
'annsam',
'studer',
'enkl',
'gäng',
'funktionsnedsättning',
'kommunal',
'huvudkont',
'åldr',
'känsl',
'beställ',
'installation',
'allmän',
'manag',
'somm',
'städ',
'fin',
'the',
'förbättring',
'drygt',
'bekväm',
'work',
'norr',
'tagit',
'behandl',
'ansvarsområd',
'förskolan',
'vikari',
'sedvan',
'kundkontak',
'sex',
'jobbannons',
'ges',
'nedan',
'material',
'minut',
'behör',
'inled',
'annon',
'iso',
'annonsering',
'barnpassning',
'saml',
'syft',
'gjort',
'utök',
'igenom',
'lugn',
'förtroend',
'tjänstepension',
'passion',
'ged',
'behandling',
'respek',
'därmed',
'samordn',
'student',
'övergrip',
'flexibelt',
'smart',
'to',
'längr',
'länd',
'ersättning',
'kr',
'privatperson',
'arbetsdag',
'råd',
'hantering',
'ibland',
'bok',
'akut',


'sats',
'beman',
'lönesättning',
'närm',
'samhäll',
'kl',
'helsingborg',
'placer',
'kvinn',
'månader',
'lss',
'kontoret',
'anställ',
'utrustning',
'lill',
'uppdater',
'etabler',
'tillverk',
'urvalet',
'värn',
'förlängning',
'fyll',
'global',
'arbetsterapeut',
'prat',
'bedömning',
'avgör',
'lyft',
'bl',
'enskild',
'specifik',
'metod',
'fall',
'sommarjobb',
'group',
'facebook',
'säk',
'förebygg',
'chan',
'kall',
'ang',
'medi',
'etc',
'dock',
'fatt',
'ber',
'februari',
'våg',
'of',
'klinisk',
'fem',
'ställning',
'medlemm',
'helst',
'framförallt',
'bild',
'gemensamt',
'beskrivning',
'felsökning',
'sysselsättning',
'främj',
'belastningsregist',
'avslut',
'budget',
'tandvård',
'tillfäll',
'uppmuntr',
'fack',
'kundbesök',
'särskild',
'näringsliv',
'färd',
'rekryteringsarbetet',
'kvalificer',
'ing',
'västerås',
'öka',
'äldr',
'ifrån',
'kollektivtrafik',
'omtank',
'we',
'säkr',
'styrk',
'centralt',


'experis',
'möjliggör',
'hemmet',
'truckkort',
'koppl',
'operativ',
'akademisk',
'europ',
'enhetschef',
'målet',
'business',
'skift',
'omsät',
'jämn',
'eftergymnasial',
'lund',
'primärvård',
'tillsättning',
'analyser',
'omvårdn',
'reparation',
'rådgivning',
'själv',
'rädd',
'offic',
'arbetsgrupp',
'påbörj',
'mynanny',
'rekryteringskanal',

'hemm',
'underlät',
'pågår',
'skydd',
'uniflex',
'förmedl',
'ännu',
'vuxn',
'örebro',
'utform',
'mm',
'finland',
'kör',
'tätt',
'serviceteknik',
'uppfyll',
'event',
'fritid',
'lerni',
'sikt',
'medverk',
'konsultuppdrag',
'ledning',
'linköping',
'befattning',
'transport',
'kurs',
'mekanik',
'respektiv',
'högskoleutbildning',
'samverk',
'alternativ',
'folktandvård',
'inkomm',
'utredning',
'tack',
'ansökningsdatum',
'äldreomsorg',
'begär',
'uppdragsgiv',
'referens',
'lyssn',
'särskilt',
'v',
'externt',
'mäng',
'verisur',
'gymnasieutbildning',


'länet',
'ämn',
'bredd',
'pris',
'ner',
'deltag',
'uppvis',
'an',
'fysioterapeut',
'små',
'fordon',
'plats',
'åren',
'rekryteringshjälp',
'nationell',
'framför',
'når',
'riktlinj',
'berät',
'läng',
'mar',
'viljan',
'certifier',
'utbud',
'handel',
'almeg',
'slut',
'placeringsort',
'laxhjalp',
'götaland',
'tillhandahåll',
'personbil',
'montör',
'internationellt',
'gentemot',
'dagsläget',
'academic',
'handled',
'utmärk',
'förbered',
'önskvärt',
'kontroll',
'träning',
'kundtjänst',
'högskol',
'redovisning',
'identifier',
'övertyg',
'föräldr',
'förmedling',
'sked',
'direktrekrytering',
'ledningsgrupp',
'arbetsled',
'ökad',
'märk',
'h',
'nordisk',
'miljon',
'anställningsvillk',
'full',
'beställning',
'kombination',
'undervis',
'städning',
'åld',
'timlön',
'rekommender',
'tank',
'närvar',
'södr',
'observer',
'regional',
'handling',
'car',
'be',
'excel',
'instruktion',
'sal',
'pedagog',
'for',
'maximer',
'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','x','y','z','å','ä','ö','ab',


'precis',
'mötet',
'arbetslag',
'projektet',
'miljard',
'operatör',
'danmark',
'tjänstgöring',
'baser',
'bank',
'utgör',
'anting',
'sprid',
'flytt',
'exam',
'sjukdom',
'ovan',
'red',
'hemtjänst',
'garanter',
'operation',
'peng',
'gymnasiet',
'kandid',
'arbetsmarknad',
'anhör',
'administrativt',
'ment',
'förslag',
'fysik',
'tillverkning',
'åtgärd',
'station',
'grundskol',
'fas',
'sträck',
'startdatum',
'st',
'rökfri',
'däreft',
'tas',
'vår',
'tung',
'medborg',
'tillsat',
'öppet',
'rapportering',
'prov',
'totalt',
'sidan',
'umeå',
'upphandl',
'regl',
'komplet',
'kännedom',
'säljteam',
'hotell',
'förstärk',
'bo',
'uthyrning',
'dagbarnvård',
'expansiv',
'fri',
'inneh',
'förskollär',
'ansik',
'privatundervisning',
'globalt',
'språkkunskap',
'funnit',
'truck',
'varakt',
'professional',
'flest',
'priv',
'tävling',
'praktik',
'producer',
'upprät',


'studentconsulting',
'personalansv',
'kundrelation',
'mediesälj',
'räkning',
'norrköping',
'rekryteringssajt',
'montering',
'verksamhetsområd',
'capio',
'varav',
'sekt',
'personuppgift',
'förbok',
'förvalt',
'beskriv',
'pedagogik',
'montico',
'halland',
'visst',
'leverans',
'tjän',
'årl',
'registerkontroll',
'ord',
'sökord',
'juni',
'absolut',
'kron',
'swed',
'effektiviser',
'sid',
'yrket',
'ses',
'jobbjustnu',
'ans',
'bryr',
'utvärder',
'vårdnadshav',
'beläg',
'kontroller',
'vatt',
'arbetspass',
'tillför',
'bb',
'part',
'friskvård',
'cnc',
'mass',
'verksamm',
'medicin',
'handlägg',
'utgångspunk',
'rad',
'insat',
'yrkeserfaren',
'utrymm',
'lead',
'aldr',
'yrk',
'vidareutbildning',
'hemsjukvård',
'expert',
'obs',
'psykolog',
'tandskötersk',
'hyr',
'alt',
'omkring',
'luft',
'växjö',
'hänsyn',
'leveran',
'fortlöp',
'bestå',
'iket',
'sammanhang',
'soln',
'igång',
'avs',
'undanbed',
'besvar',


'upphandling',
'syn',
'beslutsväg',
'administratör',
'aktuellt',
'stämm',
'känneteckn',
'giv',
'hygi',
'klättr',
'film',
'rekommendation',
'psykiatri',
'kön',
'ansvaret',
'gräns',
'medarbetar',
'specialitet',
'intyg',
'fått',
'val',
'sport',
'presenter',
'företräd',
'samarbetet',
'vd',
'sinn',
'inn',
'bemanningsbolag',
'operativt',
'eftermiddag',
'ordinari',
'rehabilitering',
'gävl',
'kock',
'övergå',
'kök',
'ärl',
'sjukhuset',
'givetvis',
'heltidstjänst',
'söd',
'bjud',
'må',
'nordic',
'tandläk',
'program',
'avseend',
'godkänd',
'timvikari',
'your',
'serv',
'partner',
'istället',
'geografisk',
'analys',
'litet',
'betyg',
'pension',
'stäng',
'teoretisk',
'eventuellt',
'administrer',
'semest',
'markn',
'knapp',
'samarbetspartner',
'lönsam',
'bered',
'distan',
'jakt',
'upprätthåll',
'omsättning',
'bakgrundskontroll',
'reception',
'etnisk',
'råvar',
'ansökningshandling',
'position',
'institution',
'socialtjänst',
'koordiner',
'munt',
'resan',
'vinn',
'luleå',
'politisk',


'hav',
'you',
'matlagning',
'are',
'relater',
'varannan',
'psykisk',
'enkel',
'complet',
'säg',
'union',
'underlag',
'vaccin',
'par',
'ytterst',
'psykiatrisk',
'affärssystem',
'haft',
'högr',
'kontaktuppgift',
'microsoft',
'stat',
'hjälpmedel',
'borås',
'åk',
'assister',
'stund',
'industrin',
'rent',
'säkerhetsprövning',
'värnamo',
'pågåend',
'folktandvard',
'sökt',
'company',
'resur',
'fre',
'beläget',
'lokalt',
'vårdgiv',
'implementer',
'omnejd',
'konc',

'fördelakt',
'elektrik',
'ram',
'sjr',
'optimer',
'säkerhetsklass',
'fisk',
'automation',
'uppstår',
'likväl',
'tillvar',
'beståend',
'ändr',
'korrek',
'blanket',
'minsk',
'kompletter',
'ren',
'tel',
'mekanisk',
'leg',
'mejl',
'fabrik',
'lokalvård',
'semesterersättning',
'förening',
'månadslön',
'finsk',
'arbetslivet',
'hälsofrämj',
'adecco',
'bokning',
'skandinavi',
'visstidsanställning',
'bemanningsuppdrag',
'rekryteringssystemet',
'custom',
'jämför',
'about',
'ritningsläsning',
'tex',
'journalsystem',
'fyllt',


'roboclean',
'tandfak',
'produktionsteknik',
'prokon',
'adapteo',
'garantilön',
'lil',
'cowi',
'demonstrer',
'ritning',
'till',
'kropp',
'retail',
'truckför',
'intervjufas',
'svets',
'dokt',
'markaryd',
'tandvårdspersonal',
'arbetstempo',
'keysolutionss',
'vvs',
'glöm',
'atentel',
'platschef',
'ring',
'hofor',
'mycronic',
'dvs',
'förenkl',
'involver',
'överblick',
'teli',
'moment',
'regelbundet',
'byggnad',
'milleteknik',
'åka',
'bort',
'rikstäck',
'mångår',
'rull',
'bostäd',
'enköping',
'aktiebolag',
'räkn',
'tv',


'lönetak',
'lkab',
'dit',
'tandhygienist',
'hårt',
'mcdonald',
'åker',
'storesupport',
'klim',
'trot',
'grundlön',
'visning',
'högskoleexam',
'telefonnumm',
'elgigant',
'uppdel',
'köket',
'detaljhandeln',
'bonus',
'vil',
'produktivitet',
'prester',
'tvåskift',
'ändå',
'skb',
'almi',
'vardforetag',
'kostnadsfrit',
'onöd',
'butikssälj',
'oatly',
'mag',
'arbetsmetod',
'prioritering',
'truckkörning',
'lov',
'aleris',
'ögat',
'falu',
'radi',
'provisionsdel',
'produktutveckling',
'snygg',
'bestämm',
'hantverk',
'chaufför',


'godkän',
'mår',
'fritt',
'lägen',
'entreprenadingenjör',
'staffing',
'begåv',
'universal',
'städmaskin',
'teknink',
'filialkont',
'oskarshamn',
'städsystem',
'intressent',
'ingenjör',
'tiqq',
'utsed',
'chatt',
'fart',
'utformning',
'ᛜ',
'lagd',
'öppettid',
'dryck',
'dfds',
'dentalrekrytering',
'elektronik',
'skog',
'mätverktyg',
'spani',
'inflyt',
'seni',
'ant',
'smak',
'avdelningschef',
'specialistläk',
'landskron',
'optimal',
'plock',
'filosofi',
'ombyggnation',
'monter',
'produktionsledning',
'uppmätning',
'operationstid',
'metodutveckling',
'dimensionering',
'arbetsstation',


'arbetsmätning', 'produktionsekonomi', 'kommunikationspunk',
'produktionseffektivisering',
'envis',
'förbättringsinsats',
'därigenom',
'företagshälsovård',
'servicenivå',
'disk',
'lagand',
'representant',
'span',
'denn',
'förebild',
'tyvärr',
'noter',
'konto',
'mjukvar',
'vidareutveckling',
'kostnad',
'aws',
'net',
'återkomm',
'torsdag',
'sortiment',
'dagar',
'plåt',
'naturligtvis',
'njut',
'eon',
'standard',
'vuxenutbildning',
'coaching',
'efterfråg',
'bollnäs',
'tävl',
'butikskedj',
'hlr',
'konsulterbjud',
'officepaketet',
'arbetserfaren',
'applikation',
'telefonsamtal',
'öga',
'vattenfall',
'medlem',
'kassan',
'dagligvaruhandeln',


'gran',
'canari',
'ykb',
'lastbil',
'maskinpark',
'underhållsmekanik',
'kommersiell',
'tyresö',
'tillvaro',
'rest',
'traditionell',
'slipp',
'servering',
'efterfrågan',
'bind',
'schemaläggning',
'cronwik',
'simlär',
'ies',
'ev',
'konsultbolag',
'trän',
'divers',
'flertalet',
'bevak',
'förvärv',
'registrering',
'grön',
'fältet',
'hus',
'köp',
'sek',
'asiatisk',
'igen',
'reservkraft',
'land',
'värm',
'botkyrk',
'såklart',
'svarsdag',
'helhetslösning',
'dental',
'visolit',
'sammanställ',
'text',
'kvällstid',

'fir',
'tech',
'mark',
'flerår',
'mötesbok',
'styck',
'massag',
'leend',
'spansk',
'vackr',
'hämt',
'ifråg',
'samman',
'framöv',
'terminal',
'expertis',
'spegl',
'atmosfär',
'verksamhetsutveckling',
'varsel',
'byggföretag',
'projektering',
'bas',
'ovanståend',
'vårdföretag',
'vack',
'trädgård',
'extraarbet',
'chopchop',
'utbildningsprogram',
'email',
'supply',
'detaljer',
'huvudkontoret',
'nästan',
'tyskland',
'valt',
'samordning',
'koll',
'inventering',
'gaml',
'årig',
'enstak',
'flöd',


'industrisnick',
'halmst',
'äger',
'formsättning',
'campus',
'fastighetsförvaltning',
'nödvänd',
'dokument',
'förs',
'fastighetsäg',
'max',
'burg',
'styrdokument',
'tilldel',
'återförsälj',
'affärsutveckling',
'åtag',
'biog',
'strax',
'lek',
'entrepren',
'matsal',
'versalift',
'msek',
'utsik',
'prestationsbaser',
'kirurgi',
'tillag',
'elever',
'villkor',
'jysk',
'bla',
'säljled',
'bemanningsföretaget',
'chain',
'täby',
'universitetet',
'deleger',
'närmst',
'styrning',
'flertal',
'testning',
'ansiktet',
'tillväxtres',
'potentiell',
'parallellt',
'teknologi',


'välmåend',
'revision',
'go',
'förverk',
'arbetsverktyg',
'varm',
'alltså',
'betalt',
'följt',
'skötsel',
'personnumm',
'cent',
'sol',
'läroplan',
'app',
'resemontör',
'onelab',
'förstånd',
'plc',
'industrielektrik',
'klass',
'nationellt',
'allr',
'beredning',
'förflyttning',
'tillvarat',
'lördag',
'biträd',
'söndag',
'vårdbemanning',
'linj',
'meny',
'lunch',
'gymnasium',
'wrknest',
'kemi',
'läkemedel',
'takt',
'namn',
'pack',
'entreprenör',
'ök',
'fastighetssköt',
'laget',
'frisk',
'säljbyrå',
'knak',
'rättvist',
'lagerarbet',
'gotland',
'tillbak',
'connect',
'sektion',
'lexman',
'newsec',
'efteråt',
'ben',
'prospek',
'grad',
'oräd',
'otro',
'addq',
'winningtemp',
'anledning',
'kyl',
'mobil',
'bistå',
'helsoklinik',
'prioritet',
'tillgodos',
'yrkesmäss',
'reko',
'marketing',
'åsed',
'svetsning',
'fullt',
'diskuter',
'komponent',
'yst',
'driftteknik',
'deadlin',
'underentreprenör',
'renhållning',
'rekryteringstjänst',
'merförsäljning',
'burgarkedj',
'restaurangbiträd',
'övervak',
'on',
'konstruktion',
'morgondag',
'tilltro',
'steget',
'kommunikatör',
'telecom',
'brand',
'supporter',
'frisör',
'mys',
'reservdel',
'östermalm',
'sett',
'skatt',
'entreprenad',
'valet',
'pagero',
'nyproduktion',
'hyresgäst',
'kassaarbet',
'utnämnd',
'gptw',
'pingisbord',
'utlov',
'gal',
'prisutdelning',
'dygn',
'anestesi',
'menyn',
'coup',
'dètat',
'urvalsfråg',
'is',
'bemanningsjobb',
'timersättning',
'protetik',
'opus',
'funktionshindr',
'pol',
'deltidsjobb',
'kundupplev',
'hsb',
'releasy',
'hemort',
'spring',
'direktförsäljning',
'jämförelsesajt',
'vårdbemanningsbolag',
'rollbeskrivning',
'lfv',
'kiw',
'nannynu',
'telefonintervju',
'optimering',
'industriell',
'elektrisk',
'bakom',
'nyckeln',
'sund',
'manuell',
'titt',
'hit',
'yabi',
'restaurangbransch',
'betald',
'uppsägningstid',
'välkänd',
'mät',
'prototyp',
'crm',
'gårdssällskapet',
'djur',
'lock',
'behåll',
'kvar',
'tysk',
'förhandling',
'resultatorienter',
'entreprenöriell',
'hjälpsam',
'liksom',
'heltidsanställning',
'stan',
'stå',
'barnet',
'skåp',
'investering',
'verksamhetschef',
'behandlingsrum',
'gjutning',
'fastighetsbolag',
'fort',
'sap',
'hugg',
'sug',
'ungefär',
'branschorganisation',
'fl',
'avhjälp',
'planet',
'svår',
'norsk',

'kass',
'generöst',
'schysst',
'hårdvar',
'off',
'modernt',
'vårdplats',
'pizz',
'skal',
'uppdragsled',
'näm',
'upplysning',
'tjänstgöringsgr',
'tng',
'huset',
'barnläk',
'rekryteringsansvar',
'kunskapsskolan',
'oris',
'victoriahem',
'konfidentiellt',
'södertörn',
'afry',
'tävlingsmännisk',
'internutbild',
'associet',
'provition',
'arbetsschem',
'premi',
'funk',
'bokningsavdelning',
'demonstration',
'direktfö',
'bim',
'soprem',
'pwc',


'skaff',
'budgetansv',
'höst',
'affärsidé',
'nuvar',
'tjänstebil',
'webbhuset',
'javascript',
'backend',
'stann',
'konfiguration',
'initialt',
'ike',
'jord',
'medborgarskap',
'fortfar',
'vetenskap',
'mänsk',
'felsök',
'mätning',
'gymnasieexam',
'humör',
'topp',
'utav',
'dörr',
'finansiell',
'framtag',
'drömm',
'remot',
'boll',
'kirun',
'upplärning',
'förstklass',
'ägar',
'datavan',
'barnsköt',
'livsstil',
'rekt',
'arbetskläd',
'tjanst',
'givn',
'snickeri',
'gilt',
'växt',
'jour',
'betongarbet',
'armering',
'betongvägg',
'betong',
'säkerhetstänk',
'forsk',
'nog',
'feedback',
'nisch',
'tjej',
'timanställning',
'annonssälj',
'förankring',
'demokratisk',
'skyld',
'lagstiftning',
'glatt',
'coromatic',
'bromm',
'tor',
'säljbolag',
'charm',
'dra',
'konsultföretag',
'uppkomn',
'underhållsavdelning',
'receptionist',
'faktur',
'närligg',
'partill',
'affärsområd',
'head',
'anordn',
'ka',
'underhållsteknik',
'behjälp',
'cad',
'pizzabag',
'invester',
'juridik',
'ljus',
'pga',
'nyrenover',
'projektchef',
'prowork',
'arbetsmiljön',
'fastighetsteknik',
'utred',
'project',
'bi',
'programmet',
'tilltal',
'konditori',
'verifier',
'fylld',
'scandic',
'omsorgsföretag',
'familjeomsorg',
'first',
'havet',
'recharg',
'marbell',
'förnuft',
'chargepanel',
'inkl',
'bus',
'härnösand',
'cdon'

     ]



def excluded_bigrams():
        return [
               ('tal', 'skrift'),
('välkomm', 'ansökan'),
('stor', 'vikt'),
('god', 'kunskap'),
('ser', 'gärn'),
('in', 'ansökan'),
('erfaren', 'arbet'),
('bland', 'ann'),
('redan', 'idag'),
('hos', 'kund'),
('tid', 'erfaren'),
('komm', 'arbet'),
('sker', 'löp'),
('enl', 'överenskomm'),
('års', 'erfaren'),
('varmt', 'välkomm'),
('skick', 'in'),
('b', 'körkort'),
('läs', 'mer'),
('svensk', 'engelsk'),
('vikt', 'person'),
('https', 'www'),
('lägg', 'stor'),
('sök', 'tjänst'),
('sist', 'ansökningsdag'),
('vill', 'arbet'),
('tjänst', 'komm'),
('person', 'lämp'),
('båd', 'tal'),
('ansökan', 'redan'),
('kunskap', 'svensk'),
('fram', 'emot'),
('ser', 'fram'),
('sök', 'vill'),
('komm', 'tillsät'),
('tillsät', 'innan'),
('jobb', 'hos'),
('när', 'samarbet'),
('meriter', 'erfaren'),
('kvalifikation', 'sök'),
('innan', 'sist'),
('hos', 'får'),
('god', 'förmåg'),
('hälso', 'sjukvård'),
('person', 'brev'),
('snart', 'möj'),
('löp', 'tjänst'),
('vill', 'jobb'),
('får', 'möj'),
('person', 'assistent'),
('lyck', 'roll'),
('arbet', 'tillsamman'),
('svensk', 'språket'),
('sver', 'störst'),
('vikt', 'del'),
('emot', 'ansökning'),
('intervju', 'sker'),
('möj', 'arbet'),
('löp', 'urval'),
('urval', 'intervju'),
('ansökning', 'via'),
('känn', 'trygg'),
('behärsk', 'svensk'),
('bemanning', 'rekryteringsföretag'),
('svensk', 'tal'),
('mer', 'information'),
('utdrag', 'ur'),
('emot', 'ansökan'),
('t', 'ex'),
('komm', 'få'),
('ska', 'kunn'),
('tar', 'emot'),
('komm', 'även'),
('anställning', 'hos'),
('hel', 'sver'),
('arbetsuppgift', 'komm'),
('västr', 'götalandsregion'),
('urval', 'sker'),
('triv', 'arbet'),
('minst', 'års'),
('start', 'omgåend'),
('arbet', 'hos'),


('allakando', 'läxhjälp'),
('god', 'möj'),
('komm', 'ske'),
('inget', 'krav'),
('vet', 'mer'),
('lägg', 'person'),
('tillsamman', 'kolleg'),
('vill', 'gör'),
('hjälp', 'kund'),
('vill', 'del'),
('stor', 'del'),
('cv', 'person'),
('arbet', 'båd'),
('vän', 'bestämt'),
('komm', 'ingå'),
('konsult', 'hos'),
('skap', 'god'),
('omfattning', 'heltid'),
('övr', 'information'),
('vill', 'vet'),
('svensk', 'båd'),
('huvudsak', 'arbetsuppgift'),
('komm', 'lägg'),
('legitimer', 'sjukskötersk'),
('fler', 'olik'),
('tillträd', 'enl'),
('van', 'arbet'),
('måndag', 'fredag'),
('hitt', 'rätt'),
('hög', 'kvalitet'),
('dag', 'kväll'),
('direktkontak', 'bemanning'),
('ta', 'emot'),
('tid', 'arbet'),
('cirk', 'medarbet'),
('ske', 'löp'),
('arbetet', 'innebär'),
('samt', 'god'),
('rekryteringsföretag', 'samt'),
('nya', 'medarbet'),
('ansökan', 'via'),
('http', 'www'),
('utbildning', 'erfaren'),
('barn', 'ungdom'),
('undanb', 'vän'),
('finn', 'möj'),
('körkort', 'krav'),
('bäst', 'möj'),
('sök', 'legitimer'),
('triv', 'roll'),
('bemanning', 'rekrytering'),
('lång', 'erfaren'),
('dag', 'arbet'),
('flyt', 'svensk'),
('vikt', 'lägg'),
('engelsk', 'tal'),
('e', 'post'),
('intervju', 'komm'),
('erfaren', 'likn'),
('tjänst', 'sök'),
('ta', 'egn'),
('utveckl', 'verksam'),
('arbet', 'aktivt'),
('roll', 'komm'),
('kunskap', 'erfaren'),
('finn', 'god'),
('ur', 'belastningsregistret'),
('ansökan', 'snart'),
('god', 'relation'),
('bl', 'a'),
('tjänst', 'innebär'),
('olik', 'typ'),
('arbet', 'när'),
('ta', 'ansv'),
('individuell', 'lönesättning'),
('kväll', 'helg'),
('ute', 'hos'),
('tjänst', 'tillsät'),
('just', 'sök'),
('sök', 'nya'),
('körkort', 'tillgång'),
('ingår', 'även'),
('via', 'mail'),
('ska', 'känn'),
('gärn', 'erfaren'),
('skick', 'ansökan'),
('uppdrag', 'hos'),
('anställd', 'hos'),
('triv', 'hos'),
('ytter', 'jobbannons'),
('olik', 'bakgrund'),
('ta', 'fram'),


('näst', 'steg'),
('hos', 'komm'),
('mer', 'www'),
('vård', 'omsorg'),
('erfaren', 'försäljning'),
('arbet', 'utifrån'),
('sök', 'sök'),
('tal', 'skriv'),
('arbet', 'barn'),
('tillsamman', 'andr'),
('dygnet', 'runt'),
('dag', 'arbetet'),
('pass', 'in'),
('kunn', 'arbet'),
('person', 'assistan'),
('arbet', 'person'),
('arbet', 'löp'),
('komm', 'jobb'),
('sver', 'led'),
('arbetsuppgift', 'roll'),
('andr', 'människ'),
('körkort', 'b'),
('tagit', 'ställning'),
('profil', 'sök'),
('lön', 'enl'),
('bestämt', 'direktkontak'),
('sen', 'januari'),
('se', 'jobb'),
('meriter', 'tid'),
('månader', 'provanställning'),
('tillgång', 'bil'),
('kund', 'finn'),
('gärn', 'in'),
('undanb', 'därför'),
('ställning', 'rekryteringskanal'),
('tyck', 'arbet'),
('sist', 'ansökningsdatum'),
('enl', 'kollektivavtal'),
('får', 'arbet'),
('försälj', 'ytter'),
('god', 'kommunikation'),
('går', 'igenom'),
('hel', 'landet'),
('genom', 'klick'),
('arbetsuppgift', 'ingår'),
('eftergymnasial', 'utbildning'),
('låt', 'intressant'),
('innan', 'ansökningstid'),
('sver', 'norg'),
('via', 'telefon'),
('uttryck', 'väl'),
('via', 'e'),
('per', 'veck'),
('arbetstid', 'förlag'),
('via', 'länk'),
('sök', 'fler'),
('region', 'skån'),
('bäst', 'förutsättning'),
('tjänst', 'tillsvidareanställning'),
('annonsering', 'rekryteringshjälp'),
('finn', 'även'),
('därför', 'vikt'),
('hög', 'krav'),
('mång', 'olik'),
('ska', 'få'),
('västr', 'götaland'),
('person', 'vill'),
('vikt', 'komm'),
('tjänst', 'heltid'),
('hemsid', 'www'),
('www', 'allakando'),
('allakando', 'se'),
('därför', 'sök'),
('rekrytering', 'sker'),
('academic', 'work'),
('gill', 'arbet'),
('minst', 'år'),
('sök', 'erfaren'),
('samt', 'andr'),
('medarbet', 'vikt'),
('få', 'möj'),
('vikt', 'roll'),
('välkomm', 'sök'),
('först', 'hand'),
('hos', 'topwork'),
('komm', 'anställd'),


('ca', 'medarbet'),
('gärn', 'mer'),
('även', 'arbet'),
('jönköping', 'län'),
('ansök', 'redan'),
('ska', 'triv'),
('se', 'laxhjalp'),
('god', 'utvecklingsmöj'),
('nya', 'kolleg'),
('rekryteringskanal', 'marknadsföring'),
('sök', 'jobbet'),
('intervju', 'löp'),
('bemanning', 'förmedling'),
('förmedling', 'rekryteringsföretag'),
('rekryteringsföretag', 'försälj'),
('läs', 'gärn'),
('tar', 'end'),
('samt', 'arbet'),
('sök', 'person'),
('inför', 'rekryteringsarbetet'),
('båd', 'kund'),
('hel', 'tid'),
('krav', 'tjänst'),
('gärn', 'sök'),
('komm', 'in'),
('dag', 'veckan'),
('bäst', 'sätt'),
('samt', 'försälj'),
('krav', 'körkort'),
('välkomm', 'kontak'),
('sök', 'därför'),
('ta', 'hand'),
('erbjud', 'annonsering'),
('hos', 'erbjud'),
('tjänst', 'kräv'),
('välkomn', 'sök'),
('försälj', 'undanb'),
('erbjud', 'god'),
('hos', 'finn'),
('komm', 'kontak'),
('del', 'arbetet'),
('förmåg', 'arbet'),
('innebär', 'komm'),
('tillsamman', 'arbet'),
('roll', 'ser'),
('via', 'hemsid'),
('tillämp', 'löp'),
('sök', 'olik'),
('bifog', 'cv'),
('polis', 'se'),
('ansökan', 'sen'),
('medarbet', 'arbet'),
('behöv', 'hjälp'),
('arbetet', 'kräv'),
('bedöm', 'likvärd'),
('information', 'start'),
('arbetet', 'sker'),
('rekrytering', 'bemanningsföretag'),
('såväl', 'tal'),
('möj', 'få'),
('båd', 'svensk'),
('komm', 'också'),
('ta', 'del'),
('rekryteringssajt', 'likn'),
('ställ', 'krav'),
('ställ', 'hög'),
('gör', 'löp'),
('ansökan', 'snar'),
('arbet', 'olik'),
('int', 'ext'),
('nöjd', 'kund'),
('vill', 'skap'),
('information', 'tjänst'),
('auktoriser', 'bemanningsföretag'),
('kontak', 'mediesälj'),
('jobb', 'tillsamman'),
('kontak', 'kund'),
('sök', 'just'),
('nya', 'sak'),


('vill', 'ge'),
('skick', 'gärn'),
('löp', 'skick'),
('engelsk', 'båd'),
('vill', 'ta'),
('arbet', 'dag'),
('sver', 'bäst'),
('internt', 'externt'),
('end', 'emot'),
('komm', 'ansvar'),
('gott', 'bemöt'),
('kund', 'sök'),
('obehindr', 'svensk'),
('ansökningstid', 'gått'),
('innan', 'anställning'),
('andr', 'lik'),
('direk', 'hos'),
('kund', 'komm'),
('ansökan', 'välkomm'),
('kund', 'konsult'),
('kompet', 'övr'),
('olik', 'bransch'),
('anpass', 'roll'),
('även', 'möj'),
('bestämt', 'kontak'),
('öppn', 'anpass'),
('roll', 'arbetsplats'),
('urvalet', 'löp'),
('övr', 'förutsättning'),
('erbjud', 'tjänst'),
('förutsättning', 'öppn'),
('arbetsplats', 'behov'),
('arbet', 'även'),
('sök', 'jobb'),
('mediesälj', 'rekryteringssajt'),
('samtid', 'enkelt'),
('igenom', 'urvalet'),
('huvudsak', 'sysselsättning'),
('polis', 'belastningsregist'),
('arbet', 'god'),
('kontak', 'kontaktperson'),
('e', 'handel'),
('språket', 'båd'),
('hemm', 'hos'),
('skrift', 'meriter'),
('m', 'm'),
('rekrytering', 'samarbet'),
('skrift', 'svensk'),
('it', 'teknik'),
('arbetsuppgift', 'sök'),
('sätt', 'in'),
('nå', 'uppsat'),
('stort', 'eget'),
('erbjud', 'erbjud'),
('roll', 'innebär'),
('ge', 'kund'),
('rekryter', 'löp'),
('arbet', 'hel'),
('tillsamman', 'övr'),
('kund', 'kolleg'),
('behöv', 'kunn'),
('hos', 'arbet'),
('högst', 'kvalitet'),
('dokumenter', 'erfaren'),
('sjukskötersk', 'uppdrag'),
('start', 'enl'),
('ta', 'näst'),
('relevant', 'utbildning'),
('erfaren', 'kunskap'),
('person', 'gill'),
('tvek', 'skick'),
('innebär', 'arbet'),
('sätt', 'kund'),
('trygg', 'anställning'),
('förmåg', 'skap'),
('ca', 'anställd'),
('van', 'förekomm'),
('arbetstid', 'varier'),
('region', 'jönköping'),
('erfaren', 'utbildning'),


('del', 'arbet'),
('arbetsuppgift', 'varier'),
('ser', 'helst'),
('egen', 'bil'),
('skap', 'förtroend'),
('arbet', 'människ'),
('arbet', 'bemanning'),
('skap', 'bäst'),
('komm', 'tillhör'),
('ansökan', 'ska'),
('rätt', 'medarbet'),
('medarbet', 'ska'),
('ser', 'också'),
('undanb', 'erbjud'),
('hjälp', 'människ'),
('arbet', 'ständ'),
('god', 'fysik'),
('gill', 'jobb'),
('kund', 'arbet'),
('gör', 'genom'),
('person', 'sök'),
('välkomm', 'in'),
('god', 'förutsättning'),
('tjänst', 'tjänst'),
('också', 'vikt'),
('annan', 'huvudsak'),
('få', 'bäst'),
('kunskap', 'engelsk'),
('dag', 'andr'),
('rekryteringshjälp', 'samband'),
('möj', 'jobb'),
('person', 'god'),
('komm', 'del'),
('arbet', 'konsult'),
('https', 'polis'),
('barn', 'ung'),
('skilln', 'dag'),
('tjänst', 'ingår'),
('arbetet', 'ingår'),
('tack', 'var'),
('ser', 'meriter'),
('sök', 'sjukskötersk'),
('ansökan', 'västr'),
('person', 'ser'),
('minst', 'två'),
('intresser', 'arbet'),
('kräv', 'god'),
('kund', 'fokus'),
('tar', 'gärn'),
('ska', 'sök'),
('runt', 'landet'),
('heltid', 'deltid'),
('förekomm', 'arbetsuppgift'),
('sök', 'erf'),
('led', 'jobb'),
('skrift', 'god'),
('meriter', 'kunskap'),
('arbet', 'utveckl'),
('arbet', 'komm'),
('meriter', 'tjänst'),
('väl', 'tal'),
('ext', 'aktör'),
('medarbet', 'nya'),
('sälj', 'hos'),
('erfaren', 'person'),
('kolleg', 'arbet'),
('befint', 'kund'),
('må', 'bra'),
('för', 'sist'),
('arbet', 'strukturer'),
('likn', 'arbetsuppgift'),
('ansök', 'via'),
('oavset', 'sök'),
('aktuell', 'tjänst'),
('vill', 'ska'),
('finn', 'tillgäng'),
('erbjud', 'kund'),
('rol', 'extrajobb'),
('möt', 'kund'),
('kund', 'bäst'),
('samt', 'erfaren'),
('ingår', 'också'),
('erbjud', 'även'),


('ge', 'god'),
('möj', 'förlängning'),
('hjälp', 'elev'),
('lär', 'känn'),
('planer', 'genomför'),
('bra', 'jobb'),
('ser', 'även'),
('partn', 'oavset'),
('idag', 'tjänst'),
('in', 'roll'),
('god', 'förstå'),
('utmaning', 'topwork'),
('enl', 'iso'),
('nya', 'kund'),
('förmåg', 'uttryck'),
('kunn', 'ta'),
('skap', 'trygg'),
('därför', 'erbjud'),
('tillsvidareanställning', 'heltid'),
('mån', 'fre'),
('vikt', 'god'),
('ser', 'självklar'),
('början', 'karriär'),
('ur', 'polis'),
('komm', 'triv'),
('god', 'result'),
('tillgång', 'egen'),
('registrer', 'ansökan'),
('emot', 'hör'),
('kund', 'räkning'),
('arbet', 'bra'),
('meriter', 'inget'),
('kväll', 'natt'),
('får', 'ta'),
('dag', 'verksam'),
('möj', 'sök'),
('bok', 'in'),
('fokus', 'ligg'),
('se', 'https'),
('relation', 'kund'),
('helt', 'enkelt'),
('sker', 'enl'),
('kort', 'beslutsväg'),
('kund', 'ska'),
('arbetsgiv', 'bedöm'),
('barnvak', 'hos'),
('ansökan', 'skick'),
('består', 'idag'),
('tillträd', 'omgåend'),
('utannonser', 'tjänst'),
('genom', 'hel'),
('båd', 'internt'),
('produk', 'tjänst'),
('marknadsföring', 'undanb'),
('via', 'www'),
('uppdraget', 'start'),
('patient', 'fokus'),
('vill', 'få'),
('hög', 'kompet'),
('stark', 'varumärk'),
('norg', 'danmark'),
('tillsät', 'tjänst'),
('sök', 'tid'),
('få', 'arbet'),
('års', 'arbetslivserfaren'),
('bygg', 'administration'),
('vid', 'ser'),
('meriter', 'arbet'),
('vänt', 'ansökan'),
('tror', 'sök'),
('ge', 'bäst'),
('sök', 'arbet'),
('fatt', 'beslut'),
('rol', 'jobbet'),
('hos', 'fler'),
('därför', 'bestämt'),
('forskning', 'utbildning'),
('sök', 'utbild'),
('barn', 'år'),
('fler', 'års'),
('led', 'utveckl'),
('komm', 'gör'),
('språk', 'meriter'),
('bakgrund', 'erfaren'),
('begär', 'utdrag'),
('egenskap', 'sök'),
('behöv', 'god'),
('fråg', 'utannonser'),
('gärn', 'tid'),
('likn', 'arbet'),
('tar', 'hand'),
('fråg', 'tjänst'),
('kort', 'varsel'),


('www', 'instagram'),
('instagram', 'com'),
('hos', 'allakando'),
('hanter', 'academic'),
('central', 'stockholm'),
('arbet', 'uppsat'),
('roll', 'behöv'),
('företag', 'arbet'),
('ger', 'råd'),
('ser', 'mångfald'),
('andr', 'ext'),
('arbetet', 'komm'),
('får', 'jobb'),
('just', 'vill'),
('ansökning', 'löp'),
('finn', 'stor'),
('hos', 'human'),
('annsam', 'ab'),
('ta', 'eget'),
('ekonomi', 'administration'),
('kund', 'får'),
('industri', 'lag'),
('offent', 'sekt'),
('komm', 'främst'),
('ansvar', 'hel'),
('även', 'god'),
('arbetstid', 'måndag'),
('sök', 'fråg'),
('här', 'kolleg'),
('b', 'personbil'),
('kund', 'medarbet'),
('lyck', 'tjänst'),
('erfaren', 'jobb'),
('enl', 'gäll'),
('förbok', 'kundbesök'),
('länk', 'https'),
('upphandl', 'avtal'),
('likn', 'roll'),
('facebook', 'com'),
('all', 'kompet'),
('dag', 'kontak'),
('svensk', 'flyt'),
('kund', 'ger'),
('förlag', 'dagtid'),
('sök', 'god'),
('omgåend', 'enl'),
('lit', 'extr'),
('vill', 'hjälp'),
('gör', 'bra'),
('timm', 'veckan'),
('ser', 'därför'),
('person', 'kontak'),
('tillsät', 'för'),
('störst', 'arbetsgiv'),
('ta', 'an'),
('får', 'utveckl'),
('per', 'år'),
('rekryteringsarbetet', 'tagit'),
('mer', 'jobb'),
('ansökan', 'omgåend'),
('anställning', 'komm'),
('ort', 'sver'),
('barn', 'hlr'),
('även', 'meriter'),
('erfaren', 'bransch'),
('medarbet', 'vill'),
('erbjud', 'anställning'),


('lätt', 'skap'),
('rekrytering', 'bemanning'),
('tillför', 'verksam'),
('sjukskötersk', 'läk'),
('leverer', 'barnpassning'),
('barnpassning', 'världsklass'),
('lär', 'mer'),
('olik', 'arbetsuppgift'),
('möj', 'person'),
('arbet', 'enl'),
('samband', 'annon'),
('kall', 'intervju'),
('arbet', 'samt'),
('pass', 'just'),
('https', 'nanny'),
('nanny', 'jobb'),
('väl', 'svensk'),
('sök', 'ska'),
('tillträd', 'snar'),
('erbjud', 'rol'),
('medarbet', 'hos'),
('annan', 'utbildning'),
('körkort', 'meriter'),
('använd', 'dag'),
('varier', 'arbetstid'),
('får', 'konsultchef'),
('får', 'chans'),
('in', 'nya'),
('övergå', 'anställning'),
('runt', 'sver'),
('finn', 'hos'),
('förstår', 'vikt'),
('del', 'kunskap'),
('bemanningsföretag', 'arbet'),
('kvalitetssäkr', 'rekryteringsprocess'),
('uppdrag', 'pass'),
('klick', 'knapp'),
('komm', 'vikt'),
('sök', 'stort'),
('två', 'års'),
('ska', 'övergå'),
('får', 'tillgång'),
('person', 'triv'),
('urval', 'välkomm'),
('arbet', 'såväl'),
('se', 'hel'),
('annons', 'stäng'),
('gärn', 'emot'),
('roll', 'ingår'),
('tillämp', 'individuell'),
('konsultchef', 'stött'),
('strukturer', 'arbet'),
('account', 'manag'),
('behöv', 'även'),
('välkomn', 'därför'),
('ansökan', 'sökord'),
('fråg', 'rör'),
('medarbet', 'rätt'),
('arbet', 'skap'),
('intress', 'arbet'),
('hos', 'båd'),
('tillsamman', 'vill'),
('välj', 'vill'),
('tjänst', 'direktrekrytering'),
('stött', 'uppdrag'),
('råd', 'rekommendation'),
('medarbet', 'kund'),
('får', 'gärn'),
('möt', 'människ'),
('står', 'inför'),
('samt', 'ansvar'),
('topwork', 'mål'),
('topwork', 'får'),
('rekommendation', 'utveckl'),
('tillsamman', 'kund'),
('därför', 'kontak'),
('här', 'gäng'),
('ser', 'får'),
('anställningsform', 'tillsvidareanställning'),
('arbet', 'minst'),


('förmåg', 'se'),
('komm', 'hanter'),
('möj', 'ta'),
('stockholm', 'göteborg'),
('tjänst', 'redan'),
('https', 'jobb'),
('olik', 'aktör'),
('annan', 'ort'),
('tyck', 'jobb'),
('roll', 'kräv'),
('privatperson', 'företag'),
('sjukskötersk', 'hos'),
('stäng', 'ner'),
('ingå', 'team'),
('ska', 'arbet'),
('komm', 'bland'),
('roll', 'arbet'),
('ingår', 'bland'),
('innebär', 'tjänst'),
('all', 'personal'),
('relevant', 'erfaren'),
('stöd', 'servic'),
('ska', 'innehåll'),
('jobb', 'komm'),
('ansvar', 'rekryter'),
('tjänst', 'placer'),
('sök', 'tillsamman'),
('mynanny', 'barnvak'),
('skriv', 'svensk'),
('fler', 'år'),
('ännu', 'bättr'),
('a', 'b'),
('bra', 'möj'),
('ska', 'må'),
('sver', 'snabb'),
('heltid', 'tillträd'),
('löp', 'vänt'),
('meriter', 'person'),
('hos', 'behöv'),
('skrift', 'samt'),
('komm', 'när'),
('komm', 'huvudsak'),
('skriv', 'obehindr'),
('lön', 'fast'),
('tjänst', 'via'),
('hopp', 'in'),
('jobb', 'försäljning'),
('aktör', 'försälj'),
('tvek', 'sök'),
('komm', 'tillsamman'),
('krav', 'tid'),
('tjänst', 'erbjud'),
('vill', 'gärn'),
('chan', 'förlängning'),
('roll', 'tror'),
('alltid', 'sätt'),
('tjänst', 'inled'),
('skap', 'nya'),
('sök', 'ny'),
('arbetsuppgift', 'består'),
('barn', 'får'),
('tillgång', 'därför'),
('länk', 'nedan'),
('profil', 'person'),
('hel', 'västr'),
('störst', 'del'),
('tjänst', 'tillsat'),
('konkurrenskraft', 'lön'),
('se', 'tjanst'),
('arbet', 'tätt'),
('vikt', 'jobb'),
('ansök', 'genom'),
('sver', 'ab'),
('rekommender', 'skick'),
('respektiv', 'annon'),
('människor', 'vardag'),
('roll', 'sälj'),
('rekrytering', 'kund'),
('krav', 'god'),
('uppdrag', 'finn'),
('hos', 'även'),


('folktandvård', 'region'),
('sker', 'genom'),
('administrativ', 'uppgift'),
('lik', 'värd'),
('engelsk', 'svensk'),
('nord', 'störst'),
('kontak', 'båd'),
('jobb', 'båd'),
('välkomm', 'skick'),
('www', 'vgregion'),
('vgregion', 'se'),
('andr', 'människor'),
('auktoriser', 'företag'),
('rätt', 'arbetsgiv'),
('kandidat', 'sen'),
('sen', 'ska'),
('skap', 'bra'),
('sen', 'året'),
('introduktion', 'nya'),
('kontaktperson', 'respektiv'),
('eget', 'driv'),
('körkort', 'bil'),
('finn', 'bransch'),
('arbetsgiv', 'arbetsplat'),
('såväl', 'kund'),
('måst', 'kunn'),
('svensk', 'näringsliv'),
('sedvan', 'uppgift'),
('skydd', 'identitet'),
('innan', 'tjänst'),
('sök', 'redan'),
('ansökan', 'rekrytering'),
('bransch', 'industri'),
('följ', 'gärn'),
('möj', 'gör'),
('led', 'rekrytering'),
('dag', 'drift'),
('natur', 'del'),
('ta', 'stort'),
('finn', 'människ'),
('medicinsk', 'sekreter'),
('får', 'bäst'),
('går', 'gymnasiet'),
('egen', 'hand'),
('topwork', 'auktoriser'),
('logistik', 'bygg'),
('administration', 'trygg'),
('professionell', 'partn'),
('topwork', 'hitt'),
('tjänst', 'båd'),
('skrift', 'b'),
('sitt', 'eget'),
('hjälp', 'andr'),
('sätt', 'arbet'),
('tjänst', 'pass'),
('arbet', 'krav'),
('almeg', 'kompetensföretag'),
('arbet', 'servic'),
('språkkunskap', 'svensk'),
('arbet', 'får'),
('ansökan', 'tar'),
('sök', 'även'),
('verksam', 'arbet'),
('hel', 'livet'),
('god', 'hälso'),
('sök', 'minst'),
('arbetstid', 'dagtid'),
('förutsättning', 'lyck'),
('inled', 'anställning'),
('ytter', 'språk'),
('pass', 'roll'),
('sen', 'åren'),
('arbetsuppgift', 'innebär'),
('kunn', 'erbjud'),
('viss', 'del'),
('elev', 'nå'),
('fyllt', 'år'),
('när', 'person'),
('jobb', 'konsult'),
('sökt', 'tjänst'),


('mångfald', 'tillför'),
('tjanst', 'tillstand'),
('bidr', 'god'),
('lik', 'vikt'),
('all', 'kontak'),
('sver', 'mest'),
('sjukskötersk', 'minst'),
('arbetsuppgift', 'sedvan'),
('fast', 'timlön'),
('idag', 'urval'),
('led', 'företag'),
('ge', 'servic'),
('sex', 'månad'),
('gå', 'in'),
('kund', 'hel'),
('region', 'uppsal'),
('önsk', 'startdatum'),
('person', 'finn'),
('ansökan', 'tjänst'),
('erbjud', 'arbet'),
('tid', 'jobb'),
('annan', 'relevant'),
('läk', 'sjukskötersk'),
('urval', 'komm'),
('tjänst', 'roll'),
('störst', 'vikt'),
('utveckl', 'båd'),
('munt', 'skrift'),
('här', 'team'),
('ansökan', 'vill'),
('tyck', 'vikt'),
('absolut', 'bäst'),
('närm', 'chef'),
('uppdrag', 'uppdraget'),
('kund', 'personal'),
('provision', 'tak'),
('fast', 'lön'),
('självständ', 'grupp'),
('erfaren', 'yrket'),
('akademisk', 'utbildning'),
('skap', 'framtid'),
('arbet', 'gör'),
('tillgäng', 'arbet'),
('fler', 'sjukskötersk'),
('dag', 'tillsamman'),
('arbetet', 'utför'),
('utifrån', 'egn'),
('arbet', 'arbet'),
('linkedin', 'com'),
('com', 'company'),
('tar', 'stort'),
('olik', 'situation'),
('god', 'erfaren'),
('jobb', 'heltid'),
('hos', 'vikt'),
('ska', 'god'),
('start', 'pågår'),
('ser', 'finn'),
('sjukvård', 'arbet'),
('registrer', 'uppgift'),
('uppgift', 'offent'),
('clear', 'sky'),
('medarbet', 'olik'),
('ansv', 'arbetsuppgift'),
('cirk', 'anställd'),
('tillstand', 'belastningsregistret'),
('samt', 'förmåg'),
('bra', 'villk'),
('se', 'led'),
('bra', 'miljö'),
('arbet', 'stor'),
('förmåg', 'kommunicer'),
('ansökan', 'ser'),
('utveckling', 'arbet'),
('offent', 'system'),


('system', 'kontak'),
('skilln', 'andr'),
('behöv', 'gör'),
('utbild', 'underskötersk'),
('ser', 'sök'),
('www', 'linkedin'),
('sedvan', 'arbetsuppgift'),
('sträv', 'jämn'),
('får', 'kontak'),
('mån', 'hjälp'),
('störst', 'möj'),
('sök', 'kund'),
('komm', 'stor'),
('vill', 'också'),
('www', 'facebook'),
('hos', 'innebär'),
('gör', 'lill'),
('ansökan', 'urval'),
('förskol', 'skol'),
('led', 'aktör'),
('ansökan', 'sök'),
('servic', 'försäljning'),
('hos', 'ska'),
('period', 'uppdrag'),
('pågår', 'tjänstgöring'),
('via', 'rekryteringssystemet'),
('ansvar', 'hälso'),
('rjl', 'se'),
('bra', 'servic'),
('möj', 'bygg'),
('lik', 'bra'),
('arbetstid', 'dag'),
('hjälp', 'fler'),
('bygg', 'långsikt'),
('krav', 'erfaren'),
('kommun', 'arbet'),
('uttryck', 'tal'),
('stockholm', 'län'),
('eventuell', 'intervju'),
('därför', 'gärn'),
('kund', 'hos'),
('medarbet', 'länk'),
('introduktion', 'ansökan'),
('tjänst', 'särskild'),
('skäl', 'registrer'),
('ref', 'nr'),
('gymnasial', 'utbildning'),
('del', 'företag'),
('arbetsuppgift', 'innefat'),
('skrift', 'krav'),
('intresser', 'jobb'),
('kommunikation', 'sök'),
('ber', 'skick'),
('viss', 'fall'),
('väl', 'funger'),
('finn', 'också'),
('götalandsregion', 'västr'),
('götalandsregion', 'finn'),
('människ', 'västr'),
('götaland', 'ser'),
('tillväxt', 'bra'),
('miljö', 'förbättr'),
('förbättr', 'folkhäls'),
('folkhäls', 'rikt'),
('kulturliv', 'god'),
('kommunikation', 'hel'),
('besök', 'introduktion'),
('se', 'introduktion'),
('götalandsregion', 'ser'),
('helst', 'registrer'),
('rekryteringssystemet', 'sök'),
('särskild', 'speciell'),
('speciell', 'skäl'),
('annon', 'bemanning'),
('jobbannons', 'västr'),
('götalandsregion', 'upphandl'),
('tjänst', 'ser'),
('klick', 'ansök'),
('information', 'företaget'),
('ansökan', 'idag'),
('får', 'även'),
('iket', 'personalpartn'),
('ska', 'även'),
('tillsat', 'innan'),
('lätt', 'ta'),
('marknad', 'bäst'),
('lön', 'individuell'),
('sök', 'roll'),
('rekrytering', 'komm'),
('krav', 'b'),
('språket', 'tal'),
('personalpartn', 'ab'),
('uppdrag', 'sök'),
('arbetsuppgift', 'arbetsuppgift'),
('rikt', 'bra'),


('måst', 'erfaren'),
('samarbet', 'övr'),
('led', 'roll'),
('kollektivtrafik', 'kultur'),
('enl', 'lss'),
('finn', 'hel'),
('komm', 'genomför'),
('region', 'stockholm'),
('vill', 'hitt'),
('börj', 'hos'),
('tjänst', 'gäll'),
('sälj', 'coach'),
('https', 'my'),
('my', 'nanny'),
('nanny', 'se'),
('ansiktet', 'utåt'),
('hitt', 'lösning'),
('tar', 'egn'),
('mångår', 'erfaren'),
('mer', 'tjänst'),
('sök', 'medarbet'),
('tjänst', 'person'),
('även', 'få'),
('erbjud', 'arbetsplat'),
('anställd', 'finn'),
('tjänst', 'avs'),
('drygt', 'anställd'),
('mer', 'hemsid'),
('varannan', 'helg'),
('människor', 'liv'),
('ansökningsdag', 'ansökan'),
('kunn', 'uttryck'),
('aktör', 'samtid'),
('eget', 'bolag'),
('överenskomm', 'omfattning'),
('urvalet', 'sker'),
('anställd', 'direk'),
('fundering', 'kring'),
('god', 'svensk'),
('förmåg', 'ta'),
('www', 'youtub'),
('youtub', 'com'),
('rekrytering', 'undanb'),
('roll', 'får'),
('ansökningsdag', 'januari'),
('sprid', 'glädj'),
('ged', 'erfaren'),
('provanställning', 'månad'),
('organisation', 'vill'),
('kontak', 'fler'),
('sök', 'relevant'),
('sök', 'två'),
('administrativt', 'arbet'),
('mång', 'möj'),
('ansökan', 'cv'),
('flyt', 'tal'),
('människ', 'olik'),
('kund', 'först'),
('kund', 'tjänst'),
('anställningsform', 'tillsvid'),
('patient', 'behov'),
('möj', 'klättr'),
('fack', 'företräd'),
('assistent', 'hos'),
('komm', 'erbjud'),
('välj', 'pass'),
('utbildning', 'enl'),
('hjälp', 'får'),
('känn', 'bra'),
('olik', 'avtal'),
('sök', 'direk'),
('laxhjalp', 'jobb'),
('talent', 'partn'),
('utveckl', 'nya'),
('jobb', 'när'),
('start', 'januari'),
('relevant', 'områd'),
('hitt', 'nya'),
('tid', 'arbetslivserfaren'),
('även', 'erfaren'),
('flerår', 'erfaren'),
('kund', 'erbjud'),
('com', 'watch'),
('watch', 'v'),
('servic', 'världsklass'),
('kompet', 'erfaren'),
('tal', 'ort'),
('går', 'vid'),
('finn', 'idag'),
('omgåend', 'gör'),
('brev', 'ansökan'),
('få', 'uppdrag'),

('person', 'hygi'),
('ansökningsdag', 'välkomm'),
('person', 'tyck'),
('exempel', 'arbetsuppgift'),
('samt', 'övr'),
('kolleg', 'komm'),
('störst', 'privat'),
('sex', 'månader'),
('egenskap', 'hos'),
('tjänst', 'rekryteringsprocess'),
('fler', 'uppdrag'),
('hjälp', 'familj'),
('bemanningsföretag', 'samtid'),
('läk', 'hitt'),
('tjänst', 'ska'),
('grundlägg', 'kunskap'),
('utför', 'arbet'),
('arbet', 'fler'),
('svensk', 'obehindr'),
('störst', 'företag'),
('ny', 'utmaning'),
('kolleg', 'kund'),
('meriter', 'god'),
('se', 'http'),
('tjänst', 'behöv'),
('vård', 'patient'),
('arbetsuppgift', 'huvudsak'),
('övr', 'region'),
('timm', 'per'),
('sjukskötersk', 'underskötersk'),
('erbjud', 'anställd'),
('sök', 'bemanningsuppdrag'),
('bemanningsuppdrag', 'via'),
('via', 'bemlo'),
('bemlo', 'hjälp'),
('fler', 'bemanningsföretag'),
('enkelt', 'jämför'),
('jämför', 'olik'),
('avtal', 'maximer'),
('maximer', 'möj'),
('möj', 'land'),
('land', 'drömjobb'),
('drömjobb', 'bemlo'),
('bemlo', 'bemlo'),
('bemlo', 'sver'),

('störst', 'jämförelsesajt'),
('jämförelsesajt', 'vårdbemanningsbolag'),
('vårdbemanningsbolag', 'mån'),
('perfek', 'bemanningsföretaget'),
('bemanningsföretaget', 'bemanningsföretag'),
('bemanningsföretag', 'sök'),
('bemlo', 'visst'),
('visst', 'uppdrag'),
('olik', 'bemanningsbolag'),
('bemanningsbolag', 'hjälp'),
('hjälp', 'bemlo'),
('bemlo', 'få'),
('få', 'förslag'),
('förslag', 'fler'),
('enkelt', 'välj'),
('just', 'bäst'),
('bäst', 'maximer'),
('ersättning', 'få'),
('villkor', 'ge'),
('ge', 'störst'),
('enl', 'rollbeskrivning'),
('läxhjälp', 'allakando'),
('företag', 'privatundervisning'),
('löp', 'annons'),
('tjänst', 'hos'),
('pedagogisk', 'sätt'),
('gärn', 'arbet'),
('verksam', 'behov'),
('förebygg', 'underhåll'),
('barn', 'elev'),
('samt', 'helg'),
('vardag', 'helg'),
('medarbet', 'sver'),
('lämp', 'övr'),
('individ', 'familjeomsorg'),
('ang', 'tjänst'),
('team', 'lead'),
('ansökan', 'komm'),
('tillsamman', 'patient'),
('ansökan', 'www'),
('barn', 'vill'),
('läxhjälp', 'https'),


('topwork', 'sök'),
('arbetsplat', 'kund'),
('lämn', 'in'),
('arbetsgiv', 'vill'),
('båd', 'priv'),
('priv', 'offent'),
('personbil', 'tillgång'),
('tillgång', 'personbil'),
('vet', 'arbetsgiv'),
('topwork', 'arbet'),
('rekrytering', 'vet'),
('vill', 'kräv'),
('kräv', 'hitt'),
('finn', 'båd'),
('sekt', 'trygg'),
('person', 'partn'),
('topwork', 'lil'),
('person', 'stort'),
('rekryteringsprocess', 'hanter'),
('urval', 'intervjufas'),
('prokon', 'ab'),
('produktion', 'arbet'),
('kund', 'markaryd'),
('ner', 'innan'),
('tillsat', 'gått'),
('gått', 'urval'),
('com', 'keysolutionss'),
('arbetsplat', 'till'),
('till', 'kund'),
('roboclean', 'se'),
('end', 'krav'),
('eget', 'schem'),
('tjänst', 'hanter'),
('rör', 'tjänst'),
('in', 'hos'),
('dokt', 'se'),
('önskemål', 'fråg'),
('kund', 'utanför'),
('jobb', 'kropp'),
('tandfak', 'se'),
('tillsamman', 'bra'),
('work', 'erbjud'),
('work', 'går'),
('runt', 'omkring'),
('erbjud', 'jobb'), ('kund', 'sver'), ('uppdraget', 'direktrekrytering'),


('jakt', 'jobb'),
('jobb', 'får'),
('intressant', 'sök'),
('utbild', 'även'),
('trygg', 'arbet'),
('jobbet', 'sälj'),
('kunn', 'utför'),
('behöv', 'tid'),
('veck', 'sök'),
('tjänst', 'topwork'),
('personal', 'grund'),
('anpass', 'olik'),
('tjän', 'peng'),
('arbet', 'dagtid'),
('tätt', 'tillsamman'),
('tvek', 'lämn'),
('person', 'jakt'),
('kunskap', 'försäljning'),
('kund', 'kräv'),
('omkring', 'sver'),
('led', 'andr'),
('tvek', 'därför'),
('människ', 'jobb'),
('utbild', 'all'),
('kunn', 'fokuser'),
('två', 'del'),
('vardforetag', 'se'),
('enkelt', 'kostnadsfrit'),
('går', 'jobbet'),
('sök', 'sälj'),
('idag', 'går'),
('alltid', 'ska'),
('sälj', 'produk'),
('del', 'samt'),
('även', 'ska'),
('uppdel', 'två'),
('även', 'person'),
('tid', 'kunskap'),
('plat', 'hos'),
('driv', 'noggran'),
('förtroend', 'hos'),
('länd', 'idag'),
('del', 'lyft'),
('förekomm', 'del'),
('eftersom', 'tjänst'),
('ibland', 'innebär'),
('innebär', 'viss'),
('såväl', 'medarbet'),

('betyd', 'behöv'),
('fas', 'behöv'),
('falu', 'kommun'),
('prat', 'bra'),
('garantilön', 'kr'),
('jobb', 'radi'),
('radi', 'vill'),
('vill', 'finn'),
('frihet', 'arbet'),
('deltid', 'låt'),
('åka', 'förbok'),
('demonstrer', 'produk'),
('båd', 'arbetstid'),
('därför', 'social'),
('situation', 'end'),
('bil', 'kunn'),
('språket', 'erbjud'),
('komm', 'lön'),
('lön', 'uppdel'),
('del', 'fast'),
('fast', 'del'),
('samt', 'provisionsdel'),
('provisionsdel', 'alltid'),
('fokuser', 'nå'),
('mål', 'utbild'),
('även', 'all'),
('personal', 'års'),
('intressant', 'tjänst'),
('olik', 'kund'),
('kund', 'runt'),
('innebär', 'res'),
('ab', 'erbjud'),
('markaryd', 'topwork'),
('kräv', 'ansvarstag'),
('kropp', 'förekomm'),
('lyft', 'arbet'),
('tempo', 'eftersom'),
('viss', 'stress'),
('stress', 'trot'),
('trot', 'högt'),
('arbetstempo', 'ändå'),
('ändå', 'säkerhetsmedvet'),
('säkerhetsmedvet', 'såväl'),
('medarbet', 'behärsk'),
('skrift', 'topwork'),
('sök', 'regelbundet'), ('anställ', 'hand'), 


('hand', 'behov'),
('behov', 'finn'),
('finn', 'tvek'),
('därför', 'lämn'),
('innebär', 'även'),
('ute', 'ny'),
('utmaning', 'prat'),
('bra', 'sak'),
('sak', 'socialt'),
('begåv', 'vill'),
('jobb', 'lönetak'),
('lönetak', 'sök'),
('sälj', 'glimt'),
('ögat', 'expansiv'),
('behöv', 'in'),
('in', 'fler'),
('fler', 'bra'),
('bra', 'människ'),
('bra', 'hos'),
('hos', 'utbild'),
('grund', 'betyd'),
('försäljning', 'sälj'),
('hos', 'roboclean'),
('roboclean', 'universal'),
('universal', 'städmaskin'),
('städmaskin', 'led'),
('led', 'teknink'),
('teknink', 'marknad'),
('marknad', 'roboclean'),
('roboclean', 'grund'),
('grund', 'expander'),
('expander', 'sälj'),
('produk', 'länd'),
('idag', 'huvudkont'),
('huvudkont', 'västerås'),
('västerås', 'filialkont'),
('filialkont', 'ligg'),
('ligg', 'oskarshamn'),
('oskarshamn', 'hofor'),
('hofor', 'sälj'),
('hos', 'utgår'),
('utgår', 'sitt'),
('eget', 'hem'),
('hem', 'åker'),
('åker', 'förbok'),
('kundbesök', 'garantilön'),
('kr', 'provision'),
('provision', 'end'), ('bil', 'flyt'),

('svensk', 'näst'),
('näst', 'stjärnsälj'),
('stjärnsälj', 'glöm'),
('glöm', 'bifog'),
('bifog', 'telefonnumm'),
('telefonnumm', 'www'),
('www', 'roboclean'),
('se', 'jobbjustnu'),
('kundbesök', 'demonstrer'),
('intress', 'försäljning'),
('tal', 'läs'),
('meriter', 'även'),
('teknisk', 'kunskap'),
('lyck', 'kräv'),
('kont', 'ligg'),
('tror', 'också'),
('fördel', 'bor'),
('kund', 'omgåend'),
('omgåend', 'behov'),
('olik', 'avdelning'),
('tandfak', 'dentalrekrytering'),
('kunskap', 'ritningsläsning'),
('ab', 'väx'),
('kund', 'uppdrag'),
('uppdrag', 'utför'),
('erfaren', 'området'),
('området', 'ser'),
('erfaren', 'områd'),
('också', 'intress'),
('intress', 'led'),
('förmåg', 'snabbt'),
('hos', 'såväl'),
('läs', 'svensk'),
('bor', 'när'),
('behöv', 'b'),
('erbjud', 'tillsvidareanställning'),
('tillsvidareanställning', 'rekryter'),
('gått', 'varmt'),
('komplet', 'leverantör'),
('rädd', 'ta'),
('erbjud', 'omväxl'),
('hjälp', 'ta'),
('mcdonald', 's'),
('leg', 'tandvårdspersonal'),
('retail', 'staffing'),
('samtal', 'mail'),
('kund', 'önskemål'),
('sver', 'erfaren'),


('erfaren', 'produktionsteknik'),
('produktionsteknik', 'driv'),
('strukturer', 'intressant'),
('tjänst', 'dessutom'),
('dessutom', 'möj'),
('arbet', 'plat'),
('kund', 'dvs'),
('dvs', 'ligg'),
('ligg', 'bort'),
('bort', 'veck'),
('hjälp', 'prokon'),
('väx', 'står'),
('inför', 'expansion'),
('expansion', 'egenskap'),
('egenskap', 'projektled'),
('projektled', 'ansv'),
('ansv', 'hjälp'),
('utveckl', 'kunder'),
('kunder', 'produktion'),
('arbet', 'produktionsteknik'),
('produktionsteknik', 'innebär'),
('innebär', 'variation'),
('variation', 'teknik'),
('teknik', 'möt'),
('möt', 'arbet'),
('tillsamman', 'operatör'),
('operatör', 'teknik'),
('teknik', 'produktionsledning'),
('produktionsledning', 'utveckl'),
('utveckl', 'produktion'),
('produktion', 'hos'),
('hos', 'respektiv'),
('respektiv', 'kund'),
('uppdrag', 'grund'),
('grund', 'oft'),
('oft', 'uppmätning'),
('uppmätning', 'operationstid'),
('operationstid', 'metodutveckling'),
('metodutveckling', 'exempelvis'),
('exempelvis', 'även'),
('även', 'inkluder'),
('inkluder', 'dimensionering'),
('dimensionering', 'hel'),
('hel', 'fabrik'),
('fabrik', 'utformning'),
('utformning', 'specifik'),
('specifik', 'arbetsstation'),
('arbetsstation', 'uppdrag'),
('utför', 'plat'),
('plat', 'innebär'),
('hos', 'olik'),
('sver', 'ibland'),
('ibland', 'fler'),
('fler', 'veck'),
('veck', 'sträck'),
('sträck', 'profil'),
('profil', 'projektled'),
('projektled', 'produktionsteknik'),
('produktionsteknik', 'ser'),
('ser', 'högskoleexam'),
('högskoleexam', 'produktionsteknik'),
('produktionsteknik', 'annan'),
('gärn', 'praktisk'),
('områd', 'projektledning'),
('projektledning', 'arbetsmätning'),
('arbetsmätning', 'produktionsekonomi'),
('produktionsekonomi', 'person'),
('ansvarsfull', 'hög'),
('integritet', 'tror'),
('andr', 'förmåg'),
('snabbt', 'skap'),
('medarbet', 'lyck'),
('kräv', 'tal'),
('svensk', 'gärn'),
('gärn', 'engelsk'),
('engelsk', 'dock'),
('dock', 'fördel'),
('när', 'kommunikationspunk'),
('kommunikationspunk', 'tjänst'),
('res', 'behöv'),
('bil', 'uppdraget'),
('direktrekrytering', 'prokon'),
('idag', 'prokon'),
('prokon', 'rikstäck'),
('rikstäck', 'komplet'),
('leverantör', 'produktionseffektivisering'),
('produktionseffektivisering', 'engagemang'),
('engagemang', 'envis'),
('envis', 'arbetsmetod'),
('arbetsmetod', 'mångår'),
('erfaren', 'tagit'),
('tagit', 'fram'),
('fram', 'mätverktyg'),
('mätverktyg', 'ger'),
('ger', 'tyd'),
('tyd', 'överblick'),
('överblick', 'produktivitet'),
('produktivitet', 'produktion'),
('produktion', 'förenkl'),
('förenkl', 'prioritering'),
('prioritering', 'förbättringsinsats'),
('förbättringsinsats', 'ger'),
('ger', 'därigenom'),
('därigenom', 'högr'),
('högr', 'effektivitet'),
('effektivitet', 'läs'),
('mer', 'prokon'),
('prokon', 'se'),
('se', 'krav'),
('extr', 'kund'),
('utanför', 'växjö'),
('arbetet', 'förlag'),
('växjö', 'sök'),
('god', 'teknisk'),
('frihet', 'styr'),
('bygg', 'nätverk'),
('engelsk', 'såväl'),
('även', 'stor'),
('driv', 'hög'),
('sök', 'års'),
('klättr', 'företaget'),
('ta', 'körkort'),
('sök', 'början'),
('span', 'in'),
('instagram', 'https'),
('keysolutionss', 'https'),
('maskin', 'truck'),
('redo', 'ta'),
('sök', 'dukt'),
('jobb', 'människ'),
('människ', 'tid'),
('sätt', 'mål'),
('konsult', 'academic'),
('väx', 'professionellt'),
('professionellt', 'bygg'),
('nätverk', 'skap'),
('skap', 'värdefull'),
('värdefull', 'kontak'),
('kontak', 'framtid'),
('framtid', 'läs'),
('mer', 'konsulterbjud'),
('sälj', 'komm'),
('komm', 'skap'),
('gran', 'canari'),
('skrift', 'tjänst'),
('tävlingsinrik', 'person'),
('mod', 'lokal'),
('behov', 'sök'),
('utanför', 'värnamo'),
('bäst', 'arbetsplats'),
('vill', 'lär'),
('bäst', 'arbetsplat'),
('låt', 'kul'),
('sätt', 'tänk'),
('par', 'års'),
('person', 'tar'),
('team', 'består'),
('möj', 'kunn'),
('lyck', 'arbetet'),
('förmåg', 'lär'),
('sök', 'positiv'),
('fordon', 'triv'),
('företaget', 'produk'),
('värnamo', 'sök'),
('kunn', 'jobb'),
('kvalifikation', 'krav'),
('del', 'produktion'),
('vikt', 'vill'),
('anställning', 'inled'),
('jobb', 'innebär'),
('ansökan', 'intervju'),
('sist', 'svarsdag'),
('tror', 'person'),
('utveckl', 'social'),
('jobbet', 'går'),
('jobb', 'tandfak'),
('heltid', 'placering'),
('intervjufas', 'information'),
('alltid', 'sträv'),
('god', 'chans'),
('kunn', 'prat'),
('olik', 'butik'),
('bra', 'grupp'),
('saml', 'in'),
('grund', 'idag'),
('person', 'ska'),
('dagtid', 'skift'),
('rol', 'sak'),
('lär', 'jobbet'),
('extr', 'produktion'),
('produktion', 'kund'),
('industrin', 'del'),
('ansvarstag', 'kvalitetsmedvet'),
('kvalitetsmedvet', 'triv'),
('kolleg', 'underhåll'),


('underhåll', 'servic'),
('kunskap', 'praktisk'),
('noggran', 'ta'),
('tjänst', 'aktuell'),
('form', 'direktrekrytering'),
('direktrekrytering', 'anställning'),
('inled', 'hos'),
('låt', 'jobb'),
('önsk', 'uppdrag'),
('försäljning', 'meriter'),
('anställ', 'löp'),
('ska', 'år'),
('se', 's'),
('steg', 'längr'),
('tjänst', 'genom'),
('konsulterbjud', 'arbetsuppgift'),
('övergrip', 'ansv'),
('relation', 'båd'),
('tjänst', 'kund'),
('sitt', 'arbet'),
('telefon', 'mail'),
('bred', 'kompet'),
('in', 'cv'),
('håll', 'rent'),
('bra', 'arbetsmiljö'),
('kunskap', 'arbet'),
('ant', 'utmaning'),
('arbet', 'formsättning'),
('komm', 'ifråg'),
('båd', 'dagtid'),
('arbet', 'heltid'),
('ska', 'lyck'),
('dagtid', 'tvåskift'),
('även', 'komm'),
('såväl', 'internt'),
('egenskap', 'avgör'),
('vilj', 'lär'),
('stark', 'tillväxt'),
('idag', 'medarbet'),
('kräv', 'också'),
('kolleg', 'bidr'),
('veck', 'veck'),
('krav', 'ska'),
('sjukskötersk', 'erfaren'),
('mail', 'telefonsamtal'),
('påbörj', 'anställning'),
('friskvårdsbidrag', 'kr'),
('gill', 'tävl'),
('hos', 'redan'),
('supply', 'chain'),
('urval', 'tjänst'),
('även', 'jobb'),
('krav', 'svensk'),
('arbet', 'företag'),
('tillsamman', 'båd'),
('mer', 'sök'),
('sök', 'erbjud'),
('ren', 'svensk'),
('måndag', 'torsdag'),
('led', 'dag'),
('hel', 'väg'),
('komm', 'besök'),
('idag', 'ca'),
('kvalité', 'arbet'),
('komm', 'bestå'),
('ute', 'fältet'),
('c', 'kort'),
('båd', 'fart'),
('fart', 'förstånd'),
('jobb', 'bra'),
('van', 'ta'),
('ifråg', 'sök'),
('sinn', 'detalj'),
('extr', 'komm'),
('behov', 'tvek'),
('sök', 'tvek'),
('erbjud', 'fast'),
('samtid', 'rol'),
('underhåll', 'maskin'),
('håll', 'ordning'),
('god', 'van'),
('gill', 'kul'),
('meriter', 'krav'),
('arbet', 'kund'),
('del', 'erfaren'),
('ansv', 'led'),
('mer', 'detaljer'),
('arbet', 'låt'),
('såklart', 'även'),
('vack', 'utsik'),
('körkort', 'möj'),
('sysselsättning', 'minst'),
('medarbet', 'gill'),
('komm', 'håll'),
('sver', 'låt'),
('hög', 'ersättning'),
('vill', 'start'),
('rädd', 'barn'),
('främst', 'jobb'),
('kunn', 'svensk'),
('gör', 'hjälp'),
('även', 'gör'),
('sälj', 'jobb'),
('utveckl', 'sätt'),
('forskning', 'utveckling'),
('familjärt', 'bolag'),
('idag', 'arbet'),
('teknisk', 'lösning'),
('anställ', 'direk'),
('erbjud', 'roll'),
('heltid', 'tillsvid'),
('anställning', 'direk'),
('person', 'ödmjuk'),
('grundlön', 'provision'),
('tillsvidareanställning', 'omfattning'),
('fast', 'månadslön'),
('tre', 'kont'),
('reko', 'marketing'),
('tyck', 'ta'),
('komm', 'varier'),
('arbetsplat', 'plåt'),
('plåt', 'åsed'),
('främst', 'verktyg'),
('arbet', 'hantverk'),
('person', 'lugn'),
('förstå', 'svensk'),
('körkort', 'c'),
('tyd', 'mål'),
('bransch', 'högst'),
('prat', 'svensk'),
('kund', 'växjö'),
('tyck', 'låt'),
('gör', 'värld'),
('värld', 'lit'),
('tjän', 'sek'),
('sek', 'm'),
('minst', 'tre'),
('server', 'gäst'),
('nå', 'dit'),
('arbet', 'hårt'),
('huvudsak', 'uppgift'),
('arbet', 'befint'),
('utbildning', 'ekonomi'),
('server', 'mat'),
('framtid', 'arbetsuppgift'),
('ser', 'god'),
('tyck', 'rol'),
('enl', 'ök'),
('kontak', 'välkomm'),
('mat', 'dryck'),
('strax', 'utanför'),
('konsultbolag', 'grund'),
('medarbet', 'utsed'),
('utsed', 'bäst'),
('bäst', 'säljbyrå'),
('säljbyrå', 'tel'),
('tel', 'teli'),
('teli', 'eon'),
('eon', 'utnämnd'),
('utnämnd', 'sver'),
('arbetsplat', 'gptw'),
('gptw', 'kont'),
('kont', 'mod'),
('lokal', 'pingisbord'),
('pingisbord', 'tv'),
('tv', 'spel'),
('spel', 'vack'),
('utsik', 'väx'),
('knak', 'sök'),
('karriär', 'gill'),
('gill', 'res'),
('res', 'gill'),
('gill', 'person'),
('utveckling', 'körkort'),
('meriter', 'måst'),
('måst', 'positiv'),
('person', 'gemensamm'),
('mål', 'tal'),
('svensk', 'arbet'),
('heltid', 'utlov'),
('utlov', 'garantilön'),
('garantilön', 'kron'),
('kron', 'sex'),
('månad', 'hjälp'),
('företaget', 'rol'),
('rol', 'gal'),
('gal', 'res'),
('res', 'tävling'),
('tävling', 'prisutdelning'),


('prisutdelning', 'rättvist'),
('rättvist', 'prestationsbaser'),
('prestationsbaser', 'arbet'),
('kul', 'ansök'),
('ansök', 'mindr'),
('mindr', 'minut'),
('minut', 'hör'),
('hör', 'dygn'),
('dygn', 'glöm'),
('glöm', 'span'),
('in', 'snygg'),
('snygg', 'kont'),
('kont', 'instagram'),
('utveckl', 'bransch'),
('coup', 'dètat'),
('sök', 'bemanningsjobb'),
('bemanningsjobb', 'jämför'),
('jämför', 'bemanningsbolag'),
('bemanningsbolag', 'hel'),
('skap', 'konto'),
('konto', 'önsk'),
('uppdrag', 'https'),
('https', 'vardforetag'),
('se', 'få'),
('få', 'erbjud'),
('erbjud', 'timersättning'),
('timersättning', 'chatt'),
('chatt', 'bemanningsbolag'),
('bemanningsbolag', 'enkelt'),
('kostnadsfrit', 'slipp'),
('slipp', 'onöd'),
('onöd', 'samtal'),
('mail', 'jobb'),
('jobb', 'vardforetag'),
('se', 'läk'),
('erfaren', 'bemanning'),
('bemanning', 'fördel'),
('fördel', 'hög'),
('ersättning', 'ing'),
('ing', 'onöd'),
('onöd', 'mail'),
('telefonsamtal', 'enkelt'),
('kostnadsfrit', 'konsult'),
('konsult', 'inget'),
('inget', 'bind'),
('bind', 'vill'),
('start', 'eget'),
('eget', 'aktiebolag'),
('aktiebolag', 'vårdföretag'),
('vårdföretag', 'hjälp'),
('hjälp', 'start'),
('start', 'aktiebolag'),
('aktiebolag', 'redovisning'),
('redovisning', 'fast'),
('fast', 'kostnad'),
('bra', 'liv'),
('övr', 'ersättning'),
('försäljning', 'motiver'),
('känn', 'vill'),
('via', 'email'),
('hänsyn', 'gdpr'),
('framgångsrik', 'företag'),
('demonstrer', 'sälj'),
('utveckl', 'intress'),
('lär', 'servic'),
('försäljning', 'sök'),
('just', 'utåtrik'),
('hög', 'mål'),
('mål', 'rädd'),
('rädd', 'jobb'),
('jobb', 'nå'),
('nå', 'kont'),
('ligg', 'västerås'),
('västerås', 'utgår'),
('utgår', 'självklart'),
('självklart', 'hemort'),
('hemort', 'jobb'),
('utveckl', 'klättr'),
('karriärsteg', 'komm'),
('arbet', 'välj'),
('välj', 'veck'),
('veck', 'vill'),
('även', 'går'),
('går', 'lik'),
('komm', 'åka'),
('kundbesök', 'alltid'),
('alltid', 'vänt'),
('vänt', 'välkomm'),
('välkomm', 'hos'),
('komm', 'demonstrer'),
('produk', 'mer'),
('information', 'produk'),
('produk', 'hitt'),
('hitt', 'roboclean'),
('jobb', 'här'),
('här', 'grupp'),
('grupp', 'gill'),
('gill', 'hitt'),
('hitt', 'rol'),
('sak', 'båd'),
('arbetstid', 'samt'),
('samt', 'efteråt'),
('efteråt', 'gäng'),
('gäng', 'alltid'),
('alltid', 'ser'),
('emot', 'tävling'),
('tävling', 'står'),
('står', 'schem'),
('schem', 'sök'),
('sök', 'lägg'),
('utåtrik', 'alltid'),
('alltid', 'ute'),
('ute', 'mer'),
('sök', 'vil'),
('vil', 'gör'),
('komm', 'steg'),
('längr', 'bransch'),
('bransch', 'lill'),
('extr', 'öka'),
('öka', 'lön'),
('lön', 'även'),
('person', 'lit'),
('extr', 'spring'),
('spring', 'ben'),
('ben', 'redo'),
('tänk', 'sätt'),
('sätt', 'tjän'),
('peng', 'redo'),
('emot', 'ser'),
('försäljning', 'social'),
('utåtrik', 'anpass'),
('end', 'två'),
('två', 'krav'),
('erfaren', 'direktförsäljning'),
('utbildning', 'försäljning'),
('arbetstid', 'mer'),
('utveckl', 'tillverk'),
('work', 'kund'),
('komm', 'anställ'),
('arbet', 'ute'),
('innebär', 'del'),
('karriär', 'utvecklingsmöj'),
('person', 'olik'),
('sen', 'teknik'),
('säkerställ', 'får'),
('ann', 'sätt'),
('andr', 'aktivitet'),
('fast', 'anställning'),
('arbet', 'ta'),
('person', 'yrkesmäss'),
('utveckling', 'komm'),
('hanter', 'ärend'),
('se', 'mer'),
('registrering', 'spansk'),
('spansk', 'personnumm'),
('krav', 'ser'),
('bidr', 'bra'),
('besit', 'god'),
('engager', 'arbet'),
('kräv', 'tid'),
('sök', 'noggran'),
('roll', 'montör'),
('engager', 'möt'),
('c', 'tung'),
('tung', 'lastbil'),
('tjänst', 'vill'),
('arbet', 'vård'),
('drygt', 'medarbet'),
('sök', 'underhållsmekanik'),
('cnc', 'operatör'),
('leverer', 'hög'),
('person', 'vikt'),
('intress', 'tyck'),
('håll', 'uppdater'),
('van', 'hanter'),
('sver', 'erbjud'),
('besök', 'gärn'),
('sök', 'gärn'),
('utbild', 'personal'),
('m', 'fl'),
('körkort', 'ser'),
('servic', 'reparation'),
('spänn', 'utveckl'),
('lätt', 'kommunicer'),
('kontak', 'såväl'),
('led', 'fördel'),
('legitimer', 'lär'),
('tjänst', 'montör'),
('hanter', 'fler'),
('ge', 'gäst'),
('led', 'styr'),
('står', 'fokus'),
('skick', 'cv'),
('fräsch', 'lokal'),
('gentemot', 'kund'),
('utveckl', 'väx'),
('komm', 'rapporter'),


('möj', 'tjänst'),
('driv', 'gör'),
('roll', 'projektled'),
('trygg', 'roll'),
('stor', 'chan'),
('stort', 'utrymm'),
('högst', 'prioritet'),
('ged', 'utbildning'),
('human', 'sök'),
('lag', 'stöd'),
('danmark', 'finland'),
('verksam', 'medarbet'),
('ansök', 'snar'),
('tjänst', 'innan'),
('kräv', 'bankid'),
('bankid', 'godkän'),
('godkän', 'använd'),
('använd', 'bankid'),
('bankid', 'tjänst'),
('full', 'potential'),
('dfds', 'professional'),
('ska', 'välj'),
('via', 'tandfak'),
('dentalrekrytering', 'tandfak'),
('led', 'rekryteringsföretag'),
('rekryteringsföretag', 'tandvård'),
('https', 'tandfak'),
('behandl', 'konfidentiellt'),
('jobb', 'förbok'),
('sälj', 'städsystem'),
('städsystem', 'roboclean'),
('roboclean', 'arbetsuppgift'),
('besök', 'prospek'),
('prospek', 'förbok'),
('förbok', 'besök'),
('besök', 'saml'),
('in', 'referens'),
('referens', 'kundbesök'),
('demonstrer', 'marknad'),
('bäst', 'städsystem'),
('städsystem', 'ansik'),
('utåt', 'sälj'),
('sälj', 'enhet'),
('enhet', 'tror'),
('motiver', 'möj'),
('kunn', 'bestämm'),
('bestämm', 'peng'),
('peng', 'ska'),
('ska', 'tjän'),
('tjän', 'samt'),
('samt', 'frihet'),
('frihet', 'sätt'),
('sätt', 'eget'),
('schem', 'tävlingsmännisk'),
('tävlingsmännisk', 'ambition'),
('ambition', 'klättr'),
('klättr', 'högt'),
('högt', 'karriär'),
('karriär', 'tid'),
('krav', 'internutbild'),
('internutbild', 'personal'),
('personal', 'sal'),
('sal', 'associet'),
('associet', 'hos'),
('får', 'grundlön'),
('grundlön', 'jobb'),
('heltid', 'räkn'),
('räkn', 'visning'),
('visning', 'garantilön'),
('garantilön', 'visning'),
('visning', 'gör'),
('gör', 'bransch'),
('högst', 'provition'),
('provition', 'rull'),
('rull', 'utbildning'),
('försäljning', 'frihet'),
('styr', 'arbetsschem'),
('arbetsschem', 'tävling'),
('tävling', 'mån'),
('mån', 'bla'),
('bla', 'vinn'),
('vinn', 'peng'),
('peng', 'premi'),
('premi', 'res'),
('res', 'krav'),
('år', 'körkort'),
('obehindr', 'anställd'),
('hos', 'påbörj'),
('anställning', 'dagar'),
('dagar', 'utbildning'),
('utbildning', 'tre'),
('kont', 'sver'),
('sver', 'direk'),
('direk', 'följt'),
('följt', 'utbildning'),
('utbildning', 'går'),
('går', 'praktik'),
('praktik', 'ihop'),
('ihop', 'ment'),
('ment', 'lär'),
('går', 'ute'),
('fältet', 'känn'),
('bra', 'anställ'),
('idag', 'jobbjustnu'),
('försäljning', 'styr'),
('styr', 'helt'),
('helt', 'egn'),
('egn', 'lön'),
('lön', 'sök'),
('just', 'person'),
('person', 'kont'),
('kont', 'hofor'),
('hofor', 'redo'),
('redo', 'tjän'),
('peng', 'vill'),
('vill', 'utgår'),
('utgår', 'såklart'),
('även', 'egen'),
('egen', 'ort'),
('ort', 'jobb'),
('karriärsteg', 'stor'),
('arbet', 'styr'),
('styr', 'eget'),
('schem', 'innebär'),
('innebär', 'funk'),
('funk', 'lik'),
('sälj', 'arbetsuppgift'),
('arbetsuppgift', 'åka'),
('kundbesök', 'bokningsavdelning'),
('bokningsavdelning', 'redan'),
('redan', 'bok'),
('in', 'demonstrer'),
('produk', 'sälj'),
('hjälp', 'nå'),
('dit', 'vill'),
('vill', 'karriärsteg'),
('karriärsteg', 'arbetsuppgift'),
('arbetsuppgift', 'mer'),
('mer', 'även'),
('även', 'peng'),
('peng', 'komm'),
('tillhör', 'trev'),
('trev', 'grupp'),
('grupp', 'social'),
('detaljer', 'komm'),
('håll', 'demonstration'),
('demonstration', 'planer'),
('planer', 'eget'),
('schem', 'utveckl'),
('utveckl', 'bättr'),
('bättr', 'sätt'),
('mål', 'klättr'),
('klättr', 'tjän'),
('tjän', 'mass'),
('mass', 'peng'),
('peng', 'sök'),
('roll', 'lägg'),
('driv', 'lill'),
('extr', 'lyck'),
('också', 'framåt'),
('framåt', 'redo'),
('bransch', 'även'),
('tävl', 'finn'),
('finn', 'gott'),
('gott', 'ser'),
('försäljning', 'lätt'),
('bil', 'behärsk'),
('erfaren', 'direktfö'),
('vill', 'fortsät'),
('komm', 'dag'),
('driv', 'projek'),
('svar', 'fråg'),
('båd', 'språk'),
('work', 'sök'),
('prat', 'skriv'),
('omgåend', 'omfattning'),
('kolleg', 'vill'),
('trivsam', 'miljö'),
('led', 'utveckling'),
('olik', 'form'),
('börj', 'jobb'),
('krav', 'annan'),
('bra', 'result'),
('även', 'del'),
('svensk', 'medborgarskap'),
('väx', 'sök'),
('förekomm', 'båd'),
('månad', 'god'),
('lkab', 's'),
('även', 'kunn'),
('minst', 'b'),
('grupp', 'samt'),
('ta', 'instruktion'),
('tempo', 'bra'),
('bör', 'självgåend'),
('utifrån', 'givn'),
('meriter', 'lägg'),


('kund', 'norr'),
('resemontör', 'kund'),
('arbetet', 'sök'),
('arbet', 'ser'),
('ser', 'person'),
('krav', 'sök'),
('medarbet', 'erbjud'),
('vill', 'ant'),
('noggran', 'ser'),
('armering', 'gjutning'),
('fysik', 'noggran'),
('bransch', 'tror'),
('tror', 'händ'),
('händ', 'sinn'),
('detalj', 'rätt'),
('ska', 'behärsk'),
('mål', 'sen'),
('sen', 'kandidat'),
('kandidat', 'ska'),
('minst', 'gymnasieutbildning'),
('innebär', 'mång'),
('se', 'ansökan'),
('arbet', 'frihet'),
('vikt', 'all'),
('extr', 'behov'),
('sidan', 'studi'),
('utveckling', 'båd'),
('stark', 'team'),
('nytt', 'rest'),
('rest', 'livet'),
('uppkomn', 'problem'),
('engager', 'person'),
('arbet', 'extr'),
('ta', 'kontak'),
('framtid', 'hållbar'),
('sinn', 'ordning'),
('mail', 'telefon'),
('sök', 'ytter'),
('head', 'of'),
('möj', 'fast'),
('god', 'mat'),
('meningsfull', 'jobb'),
('ansvarsfull', 'god'),
('ta', 'tillvar'),
('kr', 'timm'),
('erbjud', 'utveckl'),
('adapteo', 'adapteo'),
('snar', 'möj'),
('led', 'nordisk'),
('planer', 'arbet'),
('behöv', 'ta'),
('del', 'kultur'),
('egenskap', 'person'),
('får', 'båd'),
('elev', 'ska'),
('får', 'utbildning'),
('kund', 'denn'),
('human', 'human'),
('rätt', 'bra'),
('överenskomm', 'övr'),
('kollektivavtal', 'tillträd'),
('särskild', 'servic'),
('lss', 'lag'),
('servic', 'viss'),
('viss', 'funktionshindr'),
('erbjud', 'meningsfull'),
('ständ', 'förbättr'),
('glädj', 'ansv'),
('rekryteringsprocess', 'innebär'),
('innebär', 'värdesät'),
('värdesät', 'egenskap'),
('jobb', 'person'),
('gärn', 'ansök'),
('snar', 'går'),
('löp', 'komm'),
('ansökan', 'läs'),
('läs', 'personal'),
('rekryteringsprocess', 'varmt'),
('emot', 'träff'),
('komm', 'led'),
('aktivt', 'arbet'),
('tjänst', 'cv'),
('rekryter', 'ged'),
('hitt', 'drömjobbet'),
('finn', 'tillgång'),
('optimal', 'assistan'),
('göteborg', 'ab'),
('inkl', 'semesterersättning'),
('professional', 'nord')

        ]
