data = [
    ['Undersköterskor, hemtjänst, hemsjukvård och äldreboende'],
    ['Grundskollärare'],
    ['Butikssäljare, fackhandel'],
    ['Lager- och terminalpersonal'],
    ['Mjukvaru- och systemutvecklare m.fl.'],
    ['Barnskötare'],
    ['Butikssäljare, dagligvaror'],
    ['Företagssäljare'],
    ['Vårdbiträden'],
    ['Städare'],
    ['Vårdare, boendestödjare'],
    ['Övriga kontorsassistenter och sekreterare'],
    ['Personliga assistenter'],
    ['Förskollärare'],
    ['Restaurang- och köksbiträden m.fl.'],
    ['Planerare och utredare m.fl.'],
    ['Lastbilsförare m.fl.'],
    ['Grundutbildade sjuksköterskor'],
    ['Maskinställare och maskinoperatörer, metallarbete'],
    ['Träarbetare, snickare m.fl.'],
    ['Fastighetsskötare'],
    ['Elevassistenter m.fl.'],
    ['Lednings- och organisationsutvecklare'],
    ['Kockar och kallskänkor'],
    ['Undersköterskor, vård- och specialavdelning'],
    ['Ekonomiassistenter m.fl.'],
    ['Installations- och serviceelektriker'],
    ['Kundtjänstpersonal'],
    ['Motorfordonsmekaniker och fordonsreparatörer'],
    ['Ingenjörer och tekniker inom elektroteknik']
]
